### ISSUE TITLE
Question: How to disable message Run 'xxxxx --help' for usage. ?

### ISSUE THREAD

**Issue by dev-drprasad** [spf13/cobra#1111]
I am working on plugin system where caller calls commands on plugin binary (built using cobra). ex: `plugin run something`.
Caller want to know if any error happens while running command and it doesn't make sense sending message `Run 'xxxxx --help' for usage.` to caller. Is there any way to disable this message ?

**Comment by jpmcb** [comment]
The `Command` struct has the following field:
```
// SilenceErrors is an option to quiet errors down stream.
SilenceErrors bool
```
Setting this to `true` will disable the "Run ... --help' for usage" output. Hope this helps!

**Comment by dev-drprasad** [comment]
@jpmcb Thanks

`SilenceErrors: true` completely silence errors.

errors like:
```
Error: invalid argument "abcd" for "hashicorp run"
Error: accepts 1 arg(s), received 2
```
are useful for caller/user to debug problems.
Just "Run ... --help' for usage" is unnecessary when cobra commands executed by other program.

Currently I see, there is no way to achieve this. But this is useful in some cases.

I would like to raise a PR for this behaviour, if maintainers wave green flag

**Comment by jpmcb** [comment]
Since errors are returned from within the Cobra API upon failure, I believe that this can be handled by your top level application code. When defining your command, disable both error output and command usage output:
```go
var myCommand = &cobra.Command{
	SilenceErrors: true,
	SilenceUsage:  true,
}
```
Then, when calling execute on this command, capture and print the error message however you like:
```go
if err := myCommand.Execute(); err != nil {
        // There was an error! Print the error message and exit. Or do whatever you'd like!
        // This includes errors like "invalid argument" etc.
	fmt.Println(err)
	os.Exit(1)
}
```
This way, you maintain complete control of the error messaging and output. The downstream client "caller" you have can then assert on the exit status of the command or the output itself.

**Comment by dev-drprasad** [comment]
@jpmcb Thanks. Your solution works for me.
