### ISSUE TITLE
Can not use the result of command `git diff` as arguments in command line

### ISSUE THREAD

**Issue by phoenix-young** [spf13/cobra#1167]
![image](https://user-images.githubusercontent.com/3194004/87660499-bd663980-c791-11ea-87d6-7202cc601f11.png)

**Comment by Luap99** [comment]
By default cobra tries to parse flags. If the output of your "command parameter" contains words starting with `-` cobra will  interpret these as flags and since you did not define them cobra throws an error.

In your case it would properly better to pipe the git output into your programm and read it from stdin.

However if you want to use it as arguments you can call it like this to indicate that there are no more flags following:
```
crv serve -- `git diff`
```
Or you can set `DisableFlagParsing: true` on your cobra command.

**Comment by phoenix-young** [comment]
Thanks a lot
