### ISSUE TITLE
Question on differences between single character and multi-character argument names.

### ISSUE THREAD

**Issue by JuergenKindler** [spf13/cobra#1324]
I have experienced a somewhat surprising behaviour with
`rootCmd.PersistentFlags().StringVarP(&Path, "path", "p", ".", "My path.")`

Whether I pass `-p/home/jki/file.txt` or `-p /home/jki/file.txt` - it will correctly pass the path to my code. :+1: 

But it appears that if I just pass `-path  /home/jki/file.txt` ( forgot the extra '-' ) I will receive 'ath' instead of '/home/jki/file.txt' in my arguments.

Not sure whether that's a bug or feature ?

**Comment by eparis** [comment]
These are posix compatible flags, not golang flags.  Long flag names require `--` since you did `-path /home/jki/file.txt` the parser decidd you were using the short version of the flag `-p` and that the filename was `ath`.  It then placed `/home/jki/file.txt` as an argument not attached to a specific flag.

This is working as expected.

**Comment by capsci** [comment]
Can we support non-posix compatible flags?
Can cobra provide put flag parser behind an interface and allow users to choose a way some non-posix complaint flag parser (npflags)?
