### ISSUE TITLE
Custom template for generators

### ISSUE THREAD

**Issue by wilsonehusin** [spf13/cobra#1354]
I'm curious if there is any interest in supporting custom template for generators. For example, I have a convention which I like for my applications using [`envconfig`](https://github.com/kelseyhightower/envconfig) because most of my applications run in a container, hence configurations over environment variables are more readable than flags.

I'd be happy to explore the implementation, though I want to know first if this is in _no fly zone_ for the maintainers 😄

**Comment by johnSchnake** [comment]
Hey @wilsonehusin! I'm not sure I understand what you are suggesting; custom template for which generators? I just became a maintainer for cobra so perhaps I'm missing some context. If this is still something you're interested in let me know, otherwise in 2wks or so I'll just close based on the age/activity on this issue.

**Comment by johnSchnake** [comment]
Hey @wilsonehusin! I'm not sure I understand what you are suggesting; custom template for which generators? I just became a maintainer for cobra so perhaps I'm missing some context. If this is still something you're interested in let me know, otherwise in 2wks or so I'll just close based on the age/activity on this issue.

**Comment by wilsonehusin** [comment]
Hey John, thanks for following up — I think with [`cobra-cli`](https://github.com/spf13/cobra-cli/) being separated to a different repository, this issue actually belongs there.

Essentially I would like to have custom templates for `cobra add COMMAND`, perhaps something like `cobra add build --template ~/.cobra/command.tmpl` or have it included in `~/.cobra.yaml`. At the moment, that template [exists in `tpl/main.go`](https://github.com/spf13/cobra-cli/blob/main/tpl/main.go) would be pretty cool to make it customizable!

**Comment by johnSchnake** [comment]
OK, I'll go ahead and close this issue then. If you want to follow up and create the issue in that repo then that'd be great.
