### ISSUE TITLE
Children flags get in rootCmd

### ISSUE THREAD

**Issue by kotyara85** [spf13/cobra#1412]
Hello everyone,
Is there a way to get back children flags in rootCmd?

```
if err := rootCmd.ExecuteContext(ctx); err != nil {
spew.Dump("Error received", err, rootCmd.Flags)
os.Exit(1)
}
```

The use case here is the I want to output error in a specific format (yaml, json) upon error return.
Right now I have to handle this in individual sub command which a lot of code copy paste

Thanks

**Comment by johnSchnake** [comment]
I dont know of a way off the top of my head, but my intuition says it shouldn't really be necessary.

You're getting an error but it could be caused by any number of things. It is typically the responsibility of the method where the error originated to provide all the necessary information so that as the error bubbles up, it can be handled appropriately.

There are all sorts of error patterns (using named errors, custom error types, etc) that you can use so that you dont have to do much logic to format it; just ask 'is it the type of error that needs to be serialized to json?'. Or the error that gets bubbled up itself could have just been put into the appropriate format in the first place (assuming it knows what that is).

Maybe you could elaborate why those sorts of approaches dont work?

**Comment by johnSchnake** [comment]
I think you should also be able to use the `cmd.ExecuteC()` instead of `Execute`. This will result in getting back the command that was run and so you can iterate over flags and such.
