### ISSUE TITLE
Required flags validation before OnInitialize functions

### ISSUE THREAD

**Issue by ZabdiAG** [spf13/cobra#1413]
As mandatory flags need to be provided by the command input, they need to be set before running `onInit` hook functions.

Testcase:
```go
package main

import (
	"log"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use: "root",
	Run: func(_ *cobra.Command, args []string) {},
}

var param string

func init() {
	rootCmd.Flags().StringVarP(&param, "param", "p", "", "a param")
	if err := rootCmd.MarkFlagRequired("param"); err != nil {
		log.Fatalf("Required param")
	}

	// Call must be called after rootCmd.MarkFlagRequired validation
	// This way, we avoid missing initialized param errors on init function
	cobra.OnInitialize(func() {
		if param == "" {
			// This should not happend, as param is mandatory
			log.Fatalf("param undefined")
		}
	})
}

func main() {
	rootCmd.Execute()
}

```

Calling:
```bash
$ go run test/main.go
2021/06/06 15:57:41 param undefined
exit status 1

$ go run test/main.go -p someval
```

Godoc OnInitialize:
```go
// OnInitialize sets the passed functions to be run when each command's
// Execute method is called.
func OnInitialize(y ...func())
```

**Comment by johnSchnake** [comment]
Seems to be nearly a duplicate of #1521 though that one isnt concerned with the OnInit calls in particular.

As I stated there, I think that the current logic should actually stand and its a shortcoming of the documentation. It seems to me that the PreRun and OnInit gives you some space to operate in before the validation occurs; this is important in case you need to alter requirements or execute some action regardless of the params.

Going to close this one since its already open in the other issue; feel free to continue the discussion there.
