### ISSUE TITLE
how do I pass a command status to Postrun in cobra cli

### ISSUE THREAD

**Issue by gbvikas** [spf13/cobra#1416]
How do I pass on the command status to PostRun call? I have requirement of posting the command status after its execution to a server

**Comment by debankur1** [comment]
> How do I pass on the command status to PostRun call? I have requirement of posting the command status after its execution to a server

What do you mean by command status? can you give an example?

**Comment by gbvikas** [comment]
Ex: Assume there is command cmd1 which gets invoked with different flags and subcommands. After each execution of the command, I need to post the command status to a metrics server to capture how many commands were successful and how many failed.

cmd1  <flags>

**Comment by debankur1** [comment]
yeah got it maybe you can try something like this

package main

import (
	"fmt"
	"github.com/spf13/cobra"
)

var cmdResult interface{}

var rootCmd = &cobra.Command{
	Use:   "cmd1",
	Short: "test cmd",
	Run: func(cmd *cobra.Command, args []string) {
		cmdResult = testRun(false)
	},
	PostRun: func(cmd *cobra.Command, args []string) {
		// Post the result .....
		fmt.Println(cmdResult)
	},
}

func Execute(){
	rootCmd.Execute()
}

func testRun(val bool)interface{}{
	if val{
		return "ok"
	}
	return fmt.Errorf("error")
}

func main()  {
	rootCmd.Execute()
}

**Comment by johnSchnake** [comment]
Going to close this since it has been a while and you did get some discussion for your question. Feel free to reopen if you feel it needs more discussion.

I personally see the pre/run/post as needing to be completely separate events. So if you need to operate on the same data as the Run code, then I would do the metrics reporting there too. I would probably just do something to wrap the results:

```
Run: func(cmd *cobra.Command, args []string) {
  logResults(doLogic(inputs))
},
```
