### ISSUE TITLE
security fix support statement of cobra

### ISSUE THREAD

**Issue by lichunl** [spf13/cobra#1421]
We used Cobra in our project. We'd like to have your support statement of Cobra for its security vulnerability fix. How frequency you will publish security vulnerability fix if there are any?

**Comment by elfahxh** [comment]
When I also use the opensource scan tool, https://github.com/jeremylong/DependencyCheck, to scan the dependencies of my project, and there are many CVEs found in indirect dependencies, as attached:

![Screen Shot 2021-06-21 at 2 26 52 PM](https://user-images.githubusercontent.com/20352053/122716387-c5c9cd00-d29c-11eb-894c-0d341e2a6f58.png)


[OpenSourceScan_cobra.xlsx](https://github.com/spf13/cobra/files/6684499/OpenSourceScan_cobra.xlsx)

**Comment by elfahxh** [comment]
After replace the dependency package github.com/spf13/viper to higher version, most of CVEs can be resolved, It looks like that most of CVEs caused by viper package:

replace github.com/spf13/viper v1.7.0 => github.com/spf13/viper v1.8.0

![Screen Shot 2021-06-22 at 4 41 17 PM](https://user-images.githubusercontent.com/20352053/122893204-b1f39900-d378-11eb-9955-735e8f93a649.png)
