### ISSUE TITLE
Hide Credential/Secrets from command history

### ISSUE THREAD

**Issue by mohsha-msft** [spf13/cobra#1422]
Hi, 

I use cobra for one of the command line project. I have a security problem where all the credential/secret are visible in command history. 
For example: While running the command I can read through the secrets provided by executing `ps -ef | grep command-name`. Is there a fix/solution for that? 

Any help will be appreciated!

**Comment by mohsha-msft** [comment]
MySQL does solve it nicely by hiding/replacing the password with asterisks (`*`).
`mysql -u username -p ******`

**Comment by ionrover2** [comment]
is there a requirement for passing in this information in plain text on command line instead of from stdout, a file, or an env var? I'm fairly certain passing creds directly as args to a program is generally considered insecure by most security professionals.

You could prompt for username and/or password once the program is executed to get around this.

**Comment by johnSchnake** [comment]
Concur with the above, there are other options:
 - prompt ([terminal](https://pkg.go.dev/golang.org/x/crypto/ssh/terminal) has support for hiding the chars read)
 - read from [env vars](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) like aws CLI and many others do
 - store them in a config file like kubectl (AWS and others often support this too)

**Comment by johnSchnake** [comment]
No more feedback from OP with a few suggestions given. Going to close as asked/answered. Feel free to reopen if you feel it needs more discussion.
