### ISSUE TITLE
How to get sub command result back to parent?

### ISSUE THREAD

**Issue by Jthomas54** [spf13/cobra#1461]
Looking through the documentation, I don't see a way to push a command's "result" back to a parent command, but it seems somewhat valuable to make the result available to the parent command.  Is there a way to do this?  I do see the side of it being limited in usage.

My specific use case it so common formatting and a global JMESPath query can be executed on whatever the command result would be.  At this time, it is just a ton of duplicate code and some global state, no huge deal, if trying to get that result back to the parent command.  It relied on the `PersistentPostRun[E]` hooked to handle this automatically.

**Comment by johnSchnake** [comment]
I think the issue is partially the fact that even in your report of the issue you have to put "result" in quotes. The idea of an error is standardized so we can bubble that up, but what would it mean to bubble up the result?

FWIW one approach that would also avoid global state is to just create a closure around the variables when you make the commands and utilize the persistentPostRun. This may be close to what you're already doing but you can avoid global state if you want to:

```
func getRootCmd() *cobra.Command{
  val:="x"
  root := &cobra.Command{
    ...
    PersistentPostRun: func(...){ //use x here}
    ...
  }
  sub := &cobra.Command{
    ...
    Run: func(...){ //set x here}
    ...
  }
  root.AddCommand(sub)
  return root
}
```

Closing due to age and the general vagueness of the idea at this point. If you want to continue the discussion, feel free to reopen.

Thanks for the submission.
