### ISSUE TITLE
Global Normalization Function Issues with Go 1.17

### ISSUE THREAD

**Issue by kensipe** [spf13/cobra#1475]
https://github.com/spf13/cobra/pull/110 Introduced global normalization, for reasons lost on me now, our project add the following check to verify.  This passed in Go 1.16 (and before) on Cobra 1.1.1 and I've checked 1.2.1 which also worked fine.  Moving to Go 1.17 the below check now fails.   I haven't had time to understand why yet but wanted to check with project owners and provide awareness for other users.

```
	if reflect.ValueOf(sub.Flags().GetNormalizeFunc()).Pointer() != reflect.ValueOf(root.Flags().GetNormalizeFunc()).Pointer() {
		t.Fatal("child and root commands should have the same normalization functions")
	}
```

Checking out the cobra project and doing a `make test` against go 1.17 passes...  So I don't know if this is a missing test... or our approach at using the lib in an unexpected way.

**Comment by johnSchnake** [comment]
It looks like you're using `GetNormalizeFunc` and not the new `GlobalNormalizationFunc`

You can see in that PR that they are checking pretty much the same way you are that it propagates and is identical.

In the issue you linked the 'offending line' link is broken too so I can't really look further.

If you're still having the issue please point me to where the issue is and I can try and repro.

**Comment by kensipe** [comment]
Thank you for the follow up and awareness.  We've moved to the new function and all is well.  Closing.  Thanks for all the value add to the OSS / Go world!
