### ISSUE TITLE
Stacking multiple subcommands using a single subcommand

### ISSUE THREAD

**Issue by saltperfect** [spf13/cobra#1526]
The issue is similar to https://github.com/spf13/cobra/issues/1168 , where I am trying to execute multiple sub commands from a single sub command.
```
package cmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var greetcmd = &cobra.Command{
	Use:   "greet",
	Short: "great a person",
}

var both = &cobra.Command{
	Use:   "both",
	Short: "greet multiple people",
	Args: cobra.ExactValidArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		argsList := strings.FieldsFunc(args[0], func(r rune) bool { return r == ',' })
		fmt.Printf("arglist: %v\n", argsList)
		for _, arg := range argsList {
			greetcmd.SetArgs([]string{arg})
			greetcmd.Execute()
		}
	},
}

var harry = &cobra.Command{
	Use:   "harry",
	Short: "greet harry",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("harry")
	},
}
var sally = &cobra.Command{
	Use:   "sally",
	Short: "greet sally",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("sally")
	},
}

func init() {
	rootCmd.AddCommand(greetcmd)
	greetcmd.AddCommand(harry)
	greetcmd.AddCommand(sally)
	greetcmd.AddCommand(both)
}
```
  When I run `mycli greet harry,sally` I get stack overflow with the `both` command running infinity. I have followed the advice given by @umarcor given here https://github.com/spf13/cobra/issues/1168#issuecomment-659478100 of executing the parent command with right set of arguments instead of calling child command's execute. 

What can I do to have a sub command under greet command which trigger's harry and sally subcommand.

**Comment by umarcor** [comment]
@saltperfect please make the example reproducible. I.e. add a 'main'  to the block and maybe change the package name, so that we can copy, paste and exec 'go run' or 'go build'.

My understanding is that you are calling the same function infinitely in a recursive way. Hence, it is doing exactly what you coded. You need to break the recursion by identifying when arg[0] does NOT contain a comma. However, greetCmd is incomplete, so it's difficult to know.

**Comment by saltperfect** [comment]
```
package main

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var greetcmd = &cobra.Command{
	Use:   "greet",
	Short: "great a person",
}

var bothCmd = &cobra.Command{
	Use:   "both",
	Short: "greet multiple people",
	Args:  cobra.ExactValidArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		argsList := strings.FieldsFunc(args[0], func(r rune) bool { return r == ',' })
		fmt.Printf("arglist: %v\n", argsList)
		for _, arg := range argsList {
			greetcmd.SetArgs([]string{arg})
			greetcmd.Execute()
		}
	},
}

var harryCmd = &cobra.Command{
	Use:   "harry",
	Short: "greet harry",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("harry")
	},
}
var sallyCmd = &cobra.Command{
	Use:   "sally",
	Short: "greet sally",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("sally")
	},
}

var rootCmd = &cobra.Command{
	Use:   "cobraissue",
	Short: "A brief description of your application",
	Long: `A longer description`,
}

func Execute() {
	cobra.CheckErr(rootCmd.Execute())
}

func init() {
	rootCmd.AddCommand(greetcmd)
	greetcmd.AddCommand(harryCmd)
	greetcmd.AddCommand(sallyCmd)
	greetcmd.AddCommand(bothCmd)
}

func main() {
	Execute()
}
```

Here is the complete snippet.
 
When I exec `go run main.go greet both harry,sally`, it runs infinitely.
From the `bothCmd`, I am executing the `greetcmd` which is the parent of `bothCmd` with arguments harry and sally which in turn should trigger `harryCmd` and `sallyCmd` respectively, instead it is calling the `bothCmd` again and again. I am also printing the arglist for reference. 
I know my code is calling itself but I am not able to figure out how I can achieve calling various subcommads in this case `harryCmd` and `sallyCmd` which are child commands to `greetcmd` from another command `bothCmd` which is also child of `greetcmd`. 

I am following the advises read from other issue asking about this exact requirement.

**Comment by umarcor** [comment]
@saltperfect, call the root comand of the application. Not the parent of the level your are doing the "weird stuff" at, but the root of the whole compilation. So, replace L23-L24 with:

```go
rootCmd.SetArgs([]string{"greet", arg})
rootCmd.Execute()
```

Then:

```
# go run main.go greet both harry,sally
arglist: [harry sally]
harry
sally
```

For the record. I can reproduce your infinite recursion behaviour. It is not because of how you are coding per se, as I thought before. It is because cobra does not support this feature explicitly and it works on the root only.

Overall, my wording in https://github.com/spf13/cobra/issues/1168#issuecomment-659478100 is not to be taken literally. In that case the parent was the root.

I hope you understand why I was being so inquisitive about a complete and reproducible example.

**Comment by saltperfect** [comment]
Thanks @umarcor
