### ISSUE TITLE
Completion cannot executed without subcommand in zsh

### ISSUE THREAD

**Issue by chengshiwen** [spf13/cobra#1569]
Issue description:
- MacOS 10.15, with Zsh & Oh-my-zsh, and completion like `git` is ok
- I build [git-mergex](https://github.com/chengshiwen/git-mergex) with cobra 1.2.1
  - The completion of `git-mergex` looks good
  - But the the completion of `git mergex` looks bad
  - Upgrade cobra 1.2.1 to 1.3.0, and the same issue still occurs
 
![demo](http://g.recordit.co/ptkPa4yAJT.gif)

**Comment by marckhouzam** [comment]
Thanks for the report @chengshiwen.

When you perform completion on `git-mergex` it is the `git-mergex` completion function that gets called and completion works.

However, when you call completion on `git mergex` it is the the `git` completion function that gets called and I assume that script is not aware of the `mergex` subcommand and its completions.

For this to work git needs to provide some kind of plugin completion solution (assuming it doesn't already).  For example the helm project provides this: https://helm.sh/docs/topics/plugins/#providing-shell-auto-completion

P.S. It's nice to see git plugins using Cobra!

**Comment by marckhouzam** [comment]
Also, I'm working on adding plugin completion support to `kubectl` which uses the same extension mechanism as git: https://github.com/kubernetes/kubernetes/pull/105867

**Comment by chengshiwen** [comment]
Thank you for your reply @marckhouzam

**Comment by marckhouzam** [comment]
@chengshiwen I got curious about how git handles plugins and if completion is possible, and it turns out it is.  
For bash, all you have to do is define a function `_git_mergex` which sets `COMPREPLY` to the proper completions.  So, if you write the function to call `git-mergex __completeNoDesc` it becomes very easy.  I've been able to get completion to work for bash for `git-mergex` by defining the following:
```
_git_mergex() {
    # Get the completions fro git-mergex directly
    comps=$(git-mergex __completeNoDesc "${words[@]:2}" 2>/dev/null)

    # Remove the completion directive provided by Cobra
    comps=${comps%:*}

    # Only keep the completions that match the prefix typed by the user
    while IFS='' read -r comp; do
        comp=$(compgen -W "$comp" -- "$cur")
        if [ -n "$comp" ]; then
            COMPREPLY+=("$comp")
        fi
    done < <(printf "%s\n" "${comps[@]}")
}
bash-5.1$ git mergex --<TAB><TAB>
--abort     --continue  --dry-run   --remove
```

I haven't looked at how to do it for zsh, but I saw it was also possible.  Here is the reference I used: https://github.com/bobthecow/git-flow-completion

**Comment by chengshiwen** [comment]
@marckhouzam Your work is so excellent and make me feel very impressed. Thank you very much for your reply during Christmas! Merry Christmas!
