### ISSUE TITLE
Enable Close Stale Actions in Github Actions Workflow

### ISSUE THREAD

**Issue by embano1** [spf13/cobra#1598]
Discussed with @johnSchnake @jpmcb whether we should enable closing stale issues/PRs to clean up some of the issues. This is a double-edged swords, since contributors typically don't like their issues closed by a bot.

However, we could find a middle-ground and triage valid/up2date issues with `lifecycle/frozen` or a related label indicating this should be fixed/is actively worked on. All other issues will be closed after e.g. 90 days of inactivity unless someone comments (bumps) the issue again. 

This typically helps to clean the number of issues significantly, reducing the perceived load on potential contributors.

**Comment by johnSchnake** [comment]
90 days without any comment or reaction seems reasonable; I agree that its really frustrating as a community member to have issues closed after 15-30d of inactivity especially if either:
 - no one ever responded and you dont feel it was even recognized
 - it was decided but no action ever taken

If we have a large window (90d), have a tag to prevent stalebot from marking approved issues, and *hopefully* have a few more people grooming the issues then I think it can make for a good experience.

The autoclose is particularly helpful for any issues where you sit in a 'waiting for more info' state for months. Rather than having to manually close those it would be nice if those cleaned themselves up.

**Comment by jpmcb** [comment]
> If we have a large window (90d), have a tag to prevent stalebot from marking approved issues, and hopefully have a few more people grooming the issues then I think it can make for a good experience.

This also sounds good to me! What should the label be for stalebot to ignore? `lifecycle/frozen`

**Comment by umarcor** [comment]
Please, before enabling a new logic/criteria, consider removing label `kind/stale` from all currently tagged issues and PRs. Multiple contributions were marked as such because of unresponsiveness in the maintenance, without contributors being able to tell otherwise.

**Comment by umarcor** [comment]
Ref: #1560.
