### ISSUE TITLE
Question about a child command added by multiple parent commands

### ISSUE THREAD

**Issue by cyberbeast** [spf13/cobra#1602]
I have set up a cobra app as follows: 

```go
var (
	setCmd = &cobra.Command{
		Use:   "set",
		Short: "set specific features on objects",
		RunE: ...
	}
	
	getCmd = &cobra.Command{
		Use:   "get",
		Short: "get specific features on objects",
		RunE: ...
	}
	
	ResourceCmd = &cobra.Command{
		Use:   "resource",
		Short: "do things with resource",
		Run: func(cmd *cobra.Command, args []string) {
			switch cmd.Parent().Name() {
				case "get":
					... do some get stuff
				case "set":
					... do some set stuff
				default:
					...not supported on this resource
			}
		}
	}
)

func init() {
	getCmd.AddCommand(ResourceCmd)
	setCmd.AddCommand(ResourceCmd)

	rootCmd.AddCommand(GetCmd)
	rootCmd.AddCommand(SetCmd)
}
```

I am trying to achieve a `CMD VERB NOUN` syntax for my app. 

- `app get resource` and `app set resource` are valid in my mind.

Now, with this setup, for `cmd.Parent().Name()`, should the value be expected to be `get` or `set`, when called with `app get resource`? In my observation, depending on which `.AddCommand()` runs most recently becomes the parent regardless of the actual call path. 

I see that `cmd.CommandPath()` also returns the same thing. 

```
$ go run main.go get env
cmd.CommandPath(): app set environment
cmd.Parent().Name(): set
```

What am I missing here? Is there any examples I can explore so that I can have my `resourceCmd` decide what to do based on whether it was invoked by the `getCmd` or the `setCmd`?

Also, I may be approaching this all wrong in my structure. I'd appreciate if there are examples of organizing this from existing/community repos. I'd love to study those.

I am targeting something like,

```bash
cmd
    root.go
    get.go #VERBS
    set.go
    resource/
         resource.go #NOUNS
````

**Comment by marckhouzam** [comment]
Hi @cyberbeast. 

Although it may seem like a better design to avoid duplicating your `resource` command definition it may actually be better to separate the two resource commands into `getResourceCmd`  and `setResourceCmd`. I find this would give you better seperation of concerns instead of having a "messy" switch statement.

Doing this will avoid the limitation you describe but would also give you the flexibility to provide a more appropriate `Short` and `Long` description, as well as a different `Args` field, etc.

I think that in practice you will find that your two `resource` commands have less in common than it might first seen.

**Comment by cyberbeast** [comment]
Hi @marckhouzam
Thank you for your input. Yeah, the more I think about it your suggestion makes sense to me.

However, I am curious as to how `kubectl` approaches this. How does it implement `kubectl get <resource>` without defining a `getResource` cmd. There might be something custom going on there perhaps?
