### ISSUE TITLE
How to define a global Flag more elegantly?

### ISSUE THREAD

**Issue by joiky** [spf13/cobra#1628]
### Now I do this:
````
var (
	FlagVerbose *pflag.Flag
	FlagDryRun  *pflag.Flag
	FlagPort    *pflag.Flag
)

func CmdNewFlagSet() *pflag.FlagSet {
	flagSet := pflag.NewFlagSet("new", pflag.ExitOnError)

	flagSet.Bool("verbose", false, "")
	flagSet.Bool("dryrun", false, "")

	FlagVerbose = flagSet.Lookup("verbose")
	FlagDryRun = flagSet.Lookup("dryrun")

	return flagSet
}

func CmdServeFlagSet() *pflag.FlagSet {
	flagSet := pflag.NewFlagSet("serve", pflag.ExitOnError)

	flagSet.Bool("verbose", false, "")
	flagSet.Bool("dryrun", false, "")
	flagSet.Int("port", 8080, "")

	FlagVerbose = flagSet.Lookup("verbose")
	FlagDryRun = flagSet.Lookup("dryrun")
	FlagPort = flagSet.Lookup("port")

	return flagSet
}
````

### the way i thought
````
var (
	FlagVerbose *pflag.Flag = pflag.NewBoolFlag(...)
	FlagDryRun  *pflag.Flag = pflag.NewBoolFlag(...)
	FlagPort    *pflag.Flag = pflag.NewIntFlag(...)
)

func CmdNewFlagSet() *pflag.FlagSet {
	flagSet := pflag.NewFlagSet("new", pflag.ExitOnError)

	flagSet.AddFlag(FlagVerbose)
	flagSet.AddFlag(FlagDryRun)

	return flagSet
}

func CmdServeFlagSet() *pflag.FlagSet {
	flagSet := pflag.NewFlagSet("serve", pflag.ExitOnError)

	flagSet.AddFlag(FlagVerbose)
	flagSet.AddFlag(FlagDryRun)
	flagSet.AddFlag(FlagPort)

	return flagSet
}

````

Am I missing something?

**Comment by johnSchnake** [comment]
If you want global flags than I think either way is fine; globals themselves aren't elegant in general. If it were me I also probably wouldn't want the flag itself to be a global. You probably want the value the flag uses to be global. In that case have the bools/strings as globals and then just reference them when binding flags.

Again, it would be better to do something similar but ensure you don't always just rely on the global:

```
type appState struct{
...
}
var globalConfigs appState

func bindStateFlags(cmd *cobra.Command, state appState) {
   cmd.Flags....
}
```

Then if you really want to use the global state you can (by passing it in) or if you want to have it scoped to a test or a method you can do that as well.

Be sure that if you're going to rely on globals that you write some method to clear out the global state; when running tests you'll want to re-init the state in case tests rely on it and/or modify the data.

Since this was just a general question I'll leave it open for a few days and then close. If you feel this answer was already sufficient, feel free to close it early.

**Comment by joiky** [comment]
thank you for your reply.

I just have a few confusions:
1. I had to write the following code repeatedly in multiple commands
````
 xxxCmd.Flags().String("foo", ...)
````
2. You need to use "foo" multiple times. Once the parameter name is adjusted, it will be very troublesome, and if you use const to predefine it, it is not intuitive.
3. If we bind to a variable, it is not easy to determine whether the flag of the bool variable is really set, so we still have to use "foo".
