### ISSUE TITLE
Does cobra support "@file.txt" flag syntax?

### ISSUE THREAD

**Issue by Warchant** [spf13/cobra#1649]
On Windows there's limit of 32k bytes per single CLI command, which makes running of longer commands impossible.
To overcome, some tools like gcc/clang/msvc use what I call "@file.txt syntax". 
It's when all flags are saved in a text file, one per line, and then consumed by the compiler like this:

```bash
gcc -Iinclude -Wall example.c      #1

# becomes
echo "-Iinclude\n-Wall\nexample.c" > flags.txt
gcc @flags.txt # functionally same as #1
```
With this syntax we can run CLI commands of arbitrary lengths on Windows.

Does cobra support this syntax?

P.S. example with python's argparse: https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

**Comment by johnSchnake** [comment]
Thats a nifty solution to the problem. I know I've encountered that, notably when working with k8s testing and wanting to specify a large list of tests manually.

I dont think there is anything baked into cobra that does this but it seems like it would be relatively to implement in an individual app:

```
... // in root cmd
if len(args) == 1 && strings.HasPrefix(args[0], "@") {
	f := strings.TrimPrefix(args[0], "@")
	b, err := os.ReadFile(f)
	if err != nil {
		panic(err)
	}
	newArgs := strings.Split(string(b), "\n")
	return restart(newArgs)	
}
...

func restart(args []string) error {
	rootCmd := getRoot()
	rootCmd.SetArgs(args)
	return rootCmd.Execute()
}
```

Thats a bit hacky but it shows its possible by just utilizing the `SetArgs` method.

```
go build && ./issue1649 -- @myargs.txt
in root with args  [@myargs.txt]
Cmd: sub1
Got args: [foo bar ]
Got flags: yay
```

That shows what it looked like when I invoked it. The only 'catch' is that I had to invoke it with `-- @myargs.txt` instead of just `@myargs.txt`. The reason was that otherwise it really wanted the root command to be invoking a subcommand and wasn't processing it as an argument.

Does this answer your question sufficiently?

**Comment by Warchant** [comment]
Yes, thank you. Would be good to have this as baked-in feature.
