### ISSUE TITLE
bool flags accept a value but do not mention taking arguments in --help output

### ISSUE THREAD

**Issue by alimpfard** [spf13/cobra#1657]
Given a bool flag like
```go
command.PersistentFlags().BoolVarP(&opts.Frobnicate, "frobnicate", "", true, "Frobnicate the output")
```
`--help` lists:
```
--frobnicate                           Frobnicate the output (default true)
```
but the parser accepts `--frobnicate false`, expected behaviour is to either disallow `--frobnicate false` or mention the optional argument in `--help` like
```
--frobnicate [bool]                           Frobnicate the output (default true)
```

**Comment by jpmcb** [comment]
If you're looking for a single "switch" flag, you'll want something like this:

```go
var bark bool

...

// use false, the "empty" value for a bool, as the default
rootCmd.PersistentFlags().BoolVarP(&bark, "woof", "", false, "prints out bark")

...

// In your command logic, use that variable
if bark {
    println("woof!")
}
```

Running this program looks like:
```
$ ./testing-app --help

...

Flags:
  -h, --help            help for testing-app
      --woof            prints out bark
```

```
$ ./testing-app
$ ./testing-app --woof
woof!
$
```

**Comment by alimpfard** [comment]
I am not looking for a switch flag, rather that (in your example), `./testing-app --woof=false` is considered valid, yet the --help output does not mention it.

**Comment by jpmcb** [comment]
A bool flag _is_ a switch flag. 

`--woof=false`, `--woof=true`, and `--woof` are all valid inputs. This is intended behavior so that a user may provide the flag by itself or with a input boolean.

Are you expecting that the default template for bool flags should mention that it's expecting a bool? Or am I missing something here?

**Comment by alimpfard** [comment]
I expect the --help output to tell me that `--woof` accepts an optional boolean argument (as it does).
To speak in...say, getopt terms, that's the difference between `option.has_arg == true` and `option.has_arg == false`; for instance:
```
$ man --ascii=true
man: option '--ascii' doesn't allow an argument
```

**Comment by jpmcb** [comment]
> I'm just asking the --help output to list its optional argument.

I think that's fair! Re-opening and we can get some community feedback

**Comment by mid-kid** [comment]
bump. This issue bit me today, as I expected it to function as `--bool-flag false` instead of `--bool-flag=false`, given that all other flag arguments are passed without the `=`, and I think not mentioning something along the lines of `--bool-flag=VALUE` in the help output isn't a very good user experience, especially since some programs prefer `--[no-]bool-flag` or other schemes for controlling flags.
