### ISSUE TITLE
Suggest required flag only after providing noun

### ISSUE THREAD

**Issue by jeffisaavs** [spf13/cobra#1670]
Is there a way to set dynamic completion for certain arguments only after other arguments are provided? If the structure of my command looks like this
```
$ root sub1 sub2 noun --flag=val
```
where `noun` and `flag` are local to `sub2`. When I type
```
$ root sub1 sub2 [tab] [tab]
```
I get a list with the valid args for `sub2` AND the required flags for `sub2`. For the above example, I would first like to get the noun suggestions returned from the `ValidArgsFunction`, and then afterwards cobra can suggest required flags.

**Comment by johnSchnake** [comment]
Hi, thanks for the question.

I'm not particularly saavy at the completion logic, but I don't think there is by default. The reason being that the flags and arguments can be interspersed so at any given location either is valid.

Someone else can let me know if I'm wrong though.

**Comment by marckhouzam** [comment]
Good question @jeffisaavs.  @johnSchnake is right that since the user can put either the required flag or the noun first, the completion logic will suggest both.  So, normally, you can't change that.  However, there may be a way to get around that but I haven't tried it to make sure it actually works.  And it is not very simple to put in place...

You could try to use a `PersistentPreRun()` on the `root` command in which you check if the command being called is the `__complete` command (`cobra.ShellCompRequestCmd`) and then do further parsing of the `args` to know what situation you are in (is the user calling `sub2`?  was `noun` already specified? etc) and then not mark the flag as required in the cases when you don't want it to be completed.  After the `PersistentPreRun()` has adjusted this, the `Run` function of the `__complete` command will be called and will perform the completions with the new settings.  Since you would only do this for the `__complete` command, it won't affect the behaviour of your program except when doing shell completion.

But as I said, I expect this to be pretty complex and may not be worth the effort.

**Comment by jeffisaavs** [comment]
@johnSchnake @marckhouzam, thanks for the responses. I'm going to try this out and see if I can get it to work. I'll report back soon.
