### ISSUE TITLE
Help.How to use multiple command with multiple flags?

### ISSUE THREAD

**Issue by DG9Jww** [spf13/cobra#1673]
What I want: `go run test.go comm1 -d xxx comm2 -a xxx`
I want to use comm1 and comm2 with their own flags at the same time
But i got an issue:
```
Error: unknown shorthand flag: 'a' in -a
Usage:
   comm1 [flags]

Flags:
  -d, --domain string   xxxxxxxxxxxxxxx
  -h, --help            help for comm1
```

my code:
```go
var (
	cmd1    = &cobra.Command{}
	cmd2    = &cobra.Command{}
	rootCmd = &cobra.Command{}
)

func main() {
	var d string
	var a string


        //
	cmd1 = &cobra.Command{
		Use: "comm1",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("1111")
			fmt.Println(d)
		},
	}
	cmd1.Flags().StringVarP(&d, "domain", "d", "", "xxxxxxxxxxxxxxx")

        //
	cmd2 = &cobra.Command{
		Use: "comm2",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("2222222")
			fmt.Println(a)
		},
	}
	cmd2.Flags().StringVarP(&a, "dirscan", "a", "", "xxxxxxxxxxxxxxx")

        //
	rootCmd = &cobra.Command{
		Run: func(cmd *cobra.Command, args []string) {
			for _, arg := range args {
				switch arg {
				case "comm1":
					cmd1.Execute()
				case "comm2":
					cmd2.Execute()
				}
			}
		},
	}
	rootCmd.AddCommand(cmd1, cmd2)
	rootCmd.Execute()
}
```

I've ever checked #726 ,but did't solve the problem.😫
Thanks so much if someone can help me🤍

**Comment by marckhouzam** [comment]
Hi @DG9Jww.  Have you tried the `TraverseChildren` option?
https://github.com/spf13/cobra/blob/b9460ccc12f650b6df2f1a75d79a279ecf219281/command.go#L195

You should set it to true on the root command.

Let us know if this is what you were looking for.

**Comment by DG9Jww** [comment]
> Hi @DG9Jww. Have you tried the `TraverseChildren` option?
> 
> https://github.com/spf13/cobra/blob/b9460ccc12f650b6df2f1a75d79a279ecf219281/command.go#L195
> 
> You should set it to true on the root command.
> 
> Let us know if this is what you were looking for.

Unfortunately no,I still got the same issue😥

**Comment by johnSchnake** [comment]
So just tinkering to give you some ideas but this is what I did:
 - remove the commands from the root. This will prevent them from being chosen as "the command that was invoked"
 - add all the flags to the root command so it doesnt error (you can just loop through and add the flagsets as a whole)

This gets everything invoked the way you want but you'll still get the problem each time since cmd1 doesnt know about flags from cmd2:

```
$ go run main.go comm1 -d dval comm2 -a aval
prerun root
dval
chose root and comm1
Error: unknown shorthand flag: 'a' in -a
Usage:
  comm1 [flags]

Flags:
  -d, --domain string   xxxxxxxxxxxxxxx
  -h, --help            help for comm1

chose root and comm2
Error: unknown shorthand flag: 'd' in -d
Usage:
  comm2 [flags]

Flags:
  -a, --dirscan string   xxxxxxxxxxxxxxx
  -h, --help             help for comm2

```

I thought about setting the flag error func on the commands to return nil, but that doesn't actually cause the error to be ignored, just exit with no error. I think that actually could be an addition: if cobra had a special class of error you could do something like this:

```
cmd1.SetFlagErrorFunc(func(command *cobra.Command, err error) error {
     return cobra.ContinueOnError
})
```

I may create an issue for that and see if it can get picked up.

However, I realized that since we added the flags to the root command, it already did all the parsing necessary so we can skip it entirely on the subcommands by setting `DisableFlagParsing=true`.

Here is the new output:
```
go run main.go comm1 -d dval comm2 -a aval
prerun root
chose root and comm1
prerun 1111
1111
dval is dval
chose root and comm2
prerun 2222
2222222
aval is aval
```

and the updated code is at this playground link: https://go.dev/play/p/KGxUqo9P-wf

but the only important change was at the end after defining the commands (I tweaked their output to better see what was parsed/ran):

```
for _, c := range []*cobra.Command{cmd1, cmd2} {
     rootCmd.Flags().AddFlagSet(c.Flags())
     c.DisableFlagParsing = true
}
rootCmd.Execute()
```

So I think those few changes (adding flags to root, disabling children flag parsing, and not adding them as children) solves your problem?

**Comment by DG9Jww** [comment]
Hi @johnSchnake 
Em.....Well,I got another question.When my different subcommands have same flags,it doesn't work as the `rootCmd` can not add few same flags.<br>However,my subcommands do has some same flags such as `comm1 -output xxx comm2 -output mmm`
