### ISSUE TITLE
completion-zsh  error

### ISSUE THREAD

**Issue by lixd** [spf13/cobra#1694]
completion display error on zsh,like this
<img width="258" alt="image" src="https://user-images.githubusercontent.com/31980412/167574369-d880e8cf-5174-40eb-8ed9-792f62cd34ba.png">

all cmd are spilted by ':'.

my env
```BASH
[root@kc-2]/tmp# echo $SHELL
/bin/zsh
[root@kc-2]/tmp# uname -a
Linux kc-2 5.4.156-1.el7.elrepo.x86_64 #1 SMP Tue Oct 26 11:19:09 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@kc-2 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@kc-2]/tmp# zsh --version
zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
```

i just do this：
```BASH
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
$ kcctl completion zsh > "${fpath[1]}/_kcctl"
```
and open a new terminal.

bytheway it works on bash.

**Comment by marckhouzam** [comment]
Hi @lixd.  I believe this is due to the older zsh v5.0.2 version.  It should not happen with zsh v5.1.

That being said, the next release of Cobra will fix this thanks to #1665.

This problem was also reported here https://github.com/kubernetes/kubernetes/issues/105587 if it helps clarify the situation for you.

If you are able to test with the master branch of Cobra that would confirm that it is indeed fixed.  Thanks.
