### ISSUE TITLE
MarkFlagsMutuallyExclusive does not work with default values

### ISSUE THREAD

**Issue by mwmahlberg** [spf13/cobra#1752]
```golang
rootCmd.Flags().BoolP("fast", "f", true, "Enable fast mode")
rootCmd.Flags().BoolP("agressive", "a", false, "Use agressive mode")
rootCmd.MarkFlagsMutuallyExclusive("fast", "agressive")
```

Now, if you run the binary with the `-a` or the `--agressive` flag set, it will happily run. Only if the `-f` or `--fast` flag is explicitly set additionally, the expected error is thrown.

**Comment by marckhouzam** [comment]
Thanks for the report @mwmahlberg.

The flag group feature focuses on the specification of flags by three user on the command-line irrespective of the flag values.  So the behaviour you are seeing is intended.

In you example of a `fast` flag and an `aggressive` flag, the program itself is responsible in dealing with any inconsistent default values.  When the user only specifies the `-a` flag on the command-line, it is up to the program to ignore the default value of the `fast` flag.  The Cobra flag group feature simplifies the verification that the user has not specified both flags on the command-line at the same time since they are marked mutually exclusive.

You can refer to the documentation if you haven't already: https://github.com/spf13/cobra/blob/main/user_guide.md#flag-groups.  You are welcomed to provide a PR if you feel the documentation should be more clear.

**Comment by pexcn** [comment]
> The flag group feature focuses on the specification of flags by the user on the command-line irrespective of the flag values. So the behaviour you are seeing is intended.

For me, there is a workaround like: https://github.com/pexcn/daily-go/commit/068d8e64f3dbfc300bd0b5f2b95dfd9f67767640
Anyone have a better solution?
