### ISSUE TITLE
markdown documents and help command should show information about deprecated flags

### ISSUE THREAD

**Issue by tharun208** [spf13/cobra#1764]
Currently, the generated markdown and the help command do not give any information about deprecated flags in the output and in the markdown. So, this might cause the user's not to know about the flags that are deprecated and might face some issues in the long run.

**Comment by johnSchnake** [comment]
The question to answer before this can be implemented is where to add the configuration.

Since the deprecation of different flags/options occurs at different times, I think it makes sense to add deprecated values by default and, if you want them hidden from docs then you have to mark them as hidden as well?

You could also make a global option like 'showDeprecatedOptions' but some may have just gotten deprecated and others about to be removed from support.

Thoughts?
