### ISSUE TITLE
Add flags after execute

### ISSUE THREAD

**Issue by theprobugmaker** [spf13/cobra#1784]
Is it possible to add flags to the command after the execution? I want to dynamically add more flags to the application.

The problem I'm having is that those additional flags will only be added if a flag `--extra-features` is present and I only have the value filled inside the `RunE` function.

If this `--extra-features` is present I want to add more flags to the application. How can I do something like that?

Thank you.

**Comment by theprobugmaker** [comment]
Does anyone know if this is possible?

**Comment by marckhouzam** [comment]
Hi @theprobugmaker .
I haven't tried but here is my educated guess.

Since you want to add flags you need to do this before`ParseFlags()` is called.  I see two options:
1. before calling `Execute()`, look for `--extra-features` in `os.Args` yourself, and add your new flags accordingly, or
2. Enable `DisableFlagParsing` on the root command and parse the flags yourself in one of the `*Run()` functions by first looking for for `--extra-features` manually, adding the new flags and then calling `ParseFlags()` yourself.  The `__complete` command does something a bit similar in `completions.go`

In your case, which is simpler than for completions, I would use the first option, personally.

I hope this helps.

**Comment by theprobugmaker** [comment]
@marckhouzam Thank you so much for taking the time to answer me, I really appreciate it.
I just found a similar issue https://github.com/spf13/cobra/issues/1758 and I tried to do the same, disabling `DisableFlagParsing`, parsing myself, adding more flags, enabling `DisableFlagParsing` again, and calling the `parse` again (just like he did) and it "worked". But I noticed that there are way more things that `Execute` does such as validation, showing the help if no argument is found, and more (I kinda feel like recreating the `Execute` method.
He created a PR to expose validation methods: https://github.com/spf13/cobra/pull/1760 (btw).
The first approach is the easiest, I actually thought about that but I needed to ask to see if there's another way (it would be really cool if this could be facilitated).
