### ISSUE TITLE
[question❓]: Data pagination

### ISSUE THREAD

**Issue by silvioprog** [spf13/cobra#1793]
Hi team.

I'm developing a small application that will allow the user to look at 50 or more lines from a database table.

So, is there any feature (even third party libraries) allowing to paginate data? Something like `git log` does, that allows to navigate in huge logs by using the arrow `up`/`down` keys, and exiting by `q` key.

TIA for any help!

**Comment by johnSchnake** [comment]
I dont know of one off the top of my head but you may just have to look around more. I've always just let that be handled by another tool so that you have the flexibility of NOT paging more easily than worrying about if you're piping to another command or having to explicitly adding another flag for something like --no-pagination.

Others may have a different experience.

Note: I tried quickly to just see what `git` was doing and its all in C so its not a library you could grab from them.
