### ISSUE TITLE
`powershell_completions.go` - Not Completing File Path

### ISSUE THREAD

**Issue by mattcargile** [spf13/cobra#1961]
It would be nice if I could get completions for file paths because of programs like [`glow.exe`](https://github.com/charmbracelet/glow) which require it. It appears based on this code that it is by design? I would expect default completion to a file path.

https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/powershell_completions.go#L200-L211

It is discussed a little below.

https://github.com/charmbracelet/glow/issues/457

**Comment by Luap99** [comment]
If ShellCompDirectiveNoFileComp is set the program explicitly requested that no path completion should be done. If ShellCompDirectiveNoFileComp is not set then it should complete paths, it has been a long time since I used powershell but this at least used to work correctly.

Reading your linked issue it seems like the issue is for other shells as well so guess this is a problem with your program not cobra itself.

**Comment by mattcargile** [comment]
I still think it is `cobra`. Usage like `oh-my-posh.exe file` + `<TAB>` won't complete file paths either.

Maybe `glow` needs the newest `cobra` build. Usage like `oh-my-posh.exe init powershell file` + `<TAB>` *does* work so I'm not sure how it is working. `oh-my-posh` only needs to pull from files on certain sub commands while `glow ` + `<TAB>` for file paths is more natural?

**Comment by mattcargile** [comment]
So I am closing this and opening the below because I think it can be solved with the below usage.

https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/active_help.md#adding-active-help-messages

And I opened the below in the main repo. Thanks @Luap99 

https://github.com/charmbracelet/glow/issues/512
