### ISSUE TITLE
[HELP][Downstream]: how to deal with dynamic flag (value) completion when flag value can be a list of comma-separated identifiers?

### ISSUE THREAD

**Issue by thediveo** [spf13/cobra#1981]
Downstream [enumflag](https://github.com/thediveo/enumflag) author here. My module provides a type-safe enumeration flag to cobra/pflag that maps enumeration names, such as "foo" and "bar" to their internal representation, such as 42 and 666.

Now I got a request to additionally support enum flag completion. I've seen the markdown document about dynamic flag (value) completion and now I'm wondering what kind of completion strings I should return in the case where a flag doesn't take a scalar but instead a slice of enum names/values?

For instane, the following examples are considered equivalent, for an enum flag that defines "foo", "bar", and "baz" enum values (names):

    hellm --mode foo,bar

    hellm --mode foo --mode bar

Now, for the first variant `--mode foo,bar`: is it possible to return completion information so that shells correctly autocomplete for `--mode foo,` and similar? What completion information do I need to return in order to support such usage?

**Comment by marckhouzam** [comment]
Hey @thediveo.  I wasn’t aware of your package. It looks interesting. Nice work.

I believe that to support completion for `hellm --mode foo,bar` you would need to return completion strings that contain the entire prefix.  So, you would truncate the `toComplete` string up to the last comma, figure out what are the possible completions to suggest, and then prefix each of those with what you truncated out of the original string.

For example:
```
cmd.RegisterFlagCompletionFunc("mode", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
        prefix := prefixUpToLastComma(toComplete)
        var comps []string
        for _, mode := range possibleModes {
           comps = append(comps, prefix+mode)
        }
         
	return comps, cobra.ShellCompDirectiveDefault
})
```

Note that I don't need to filter the possibleModes on the user input. That's because the shells will only present the choices you've returned if they match three user input.  But some shells (zsh and fish) can do smart matching so it’s better to return more choices than less

**Comment by thediveo** [comment]
I've made good progress and am in the process of ensuring test coverage. Thank you very much for your help!

**Comment by marckhouzam** [comment]
@thediveo in my example I used `cobra. ShellCompDirectiveDefault` but now that I think about it, for a well defined enum lidt, you probably don’t want to show files as completions. So you should use: `cobra. ShellCompDirectiveNoFileComp`

**Comment by thediveo** [comment]
@marckhouzam ah, thank you very much! As enumflag supports both scalar and slice enum flags, this then should be:
- scalar: `ShellCompDirectiveNoFileComp`
- slice: `ShellCompDirectiveNoFileComp`, but can this be combined with `ShellCompDirectiveNoSpace`?

**Comment by marckhouzam** [comment]
Yes you can combine completion directives using the bit-or operator: `return comps, cobra.ShellCompDirectiveNoFileComp | cobra.ShellCompDirectiveNoSpace`
