### ISSUE TITLE
Discussion about completion command

### ISSUE THREAD

**Issue by JunNishimura** [spf13/cobra#2004]
I have a suggestion and discussion rather than a question or an issue regarding completion command.

I believe that the completion command is one of the great features of cobra. However, I think there is room for improvement in the way the functionality is provided to users.

The existing completion command generates an autocompletion script and outputs it to the terminal. My first impression is that a lot of codes is suddenly output and I have no idea what it is or what to do next. I believe that this is not only me, but many people who are not familiar with cobra may feel the same way. This is because the user's expectation is not that the shell script will be output to the terminal, but that the autocompletion script will be saved to a file and auto-completion will be prepared.

So, I think it would be more user-friendly to have the autocompletion script automatically written to the shell completion file when the completion command is executed.

e.g. 
```zsh
$ cobra-test completion zsh
auto completion script was written in $HOME/.zsh/completion/_cobra-test
```

Even if writing to the file by default is problematic, I think we should at least provide a flag to write to the file, like the --global flag in Git's config command.

e.g.
```zsh
$ cobra-test completion zsh --global
auto completion script was written in $HOME/.zsh/completion/_cobra-test
```

However, the path to the shell completion file is environment-dependent, so it seems a bit more difficult to make the implementation flexible enough to handle that.

If you would consider some kind of modification or addition of functionality, I would be happy to help, so please don't hesitate to let me know.

The above is what I feel as a cobra user, and I would love to hear your opinions!

**Comment by marckhouzam** [comment]
Thanks for bringing up the discussion @JunNishimura, providing a good user experience is something I think is very important. 

Let’s start with a little context. 

The cobra-provided completion command is only enabled if the project using cobra does not have its own completion command already.   For example, kubectl and helm provide their own completion command (because before there was no such command provided by cobra).  This also means that any project can provide their own version of the completion command, and decide to output to a file instead of printing to screen (cobra already has APIs to do that). 

But although there is such flexibility, I agree that having the best default completion command is still a good goal.

Now, the current behaviour of the completion command (outputting to the screen) is based on how kubectl, helm and some other projects had implemented their own version. It therefore seemed the right choice to follow the trend and what the user was experiencing at the time.

Another important point is that the completion command is not really meant for users. Normally a tool is installed through a package manager and it’s the package manager that calls the completion command. Because of that, some projects have decided to hide the default completion command as they don’t feel their users should have to deal with it. It should all be done automatically by the package manager or by following specific instructions. 

All that being said, I wouldn’t be opposed to extending the completion command in a backwards-compatible way with a `-f` flag or something to give the user the option to write to a specified file. 

But in all honesty, this is the first time I’ve seen such a request, so maybe it’s not that needed?

**Comment by JunNishimura** [comment]
@marckhouzam 
Thanks for the detailed explanation. 

Knowing the context helped me understand why completion command is offered in its current form.

It would be useful to have this feature, but it is not essential, so there seems to be no need to implement it right now. I think it would be better to think about implementing it after we get more opinions that are same as mine.

Perhaps this may be that I'm just too lazy to bother writing to the file manually😂

Anyway, I'm glag that we could discuss the points I was wondering about, thank you!
