### ISSUE TITLE
add command inherit author info

### ISSUE THREAD

**Issue by zh-lab** [spf13/cobra#238]
When I init an app use: `cobra init test  -a "XXX"`

Got root.go with:
```
// Copyright © 2016 XXX
//
```

And then I add a command with: `cobra add get`
In get.go:
```
// Copyright © 2016 NAME HERE <EMAIL ADDRESS>
//
```

Is that a good idea to inherit init's -a flag maybe?

**Comment by spf13** [comment]
The commands run without state. If you would like persistence Cobra supports a config file where you can set the author field which would apply as the default for all commands called. 

Perhaps it would make sense to have cobra add inspect the copyright line set in the root.go file and use that as it's default but that feels too magical to me since copyright is something that should be declared, not assumed and the persistent option via config  is already available.

Perhaps we need better documentation on this.
