### ISSUE TITLE
Generated bash autocomplete emits error with every tab-completion on OS X

### ISSUE THREAD

**Issue by cuongdo** [spf13/cobra#240]
When I generate a bash autocomplete file and use it on OS X El Capitan, I get the following error when performing a tab completion:

```
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

It looks like `declare -a` (lower-case 'a') is the right thing to use to declare an associative array on OS X's variant of bash.

**Comment by bdarnell** [comment]
Bash didn't have associative arrays until [version 4](http://www.tldp.org/LDP/abs/html/bashver4.html); OSX has 3.2.57. `declare -a` is a plain (indexed) array so it doesn't look like replacing `-A` with `-a` will work.

**Comment by anthonyfok** [comment]
For reference:

* This bug was introduced with Pull Request #205, commit as 60b8213 on 2015-12-24, roughly a month and a half ago.
* OS X, even the very latest version, ships a very outdated bash 3.x because Apple supposedly does not want to touch anything that is licensed under GPLv3 like Bash 4, see http://blog.bennycornelissen.nl/bash-4-x-on-osx-the-bash-that-apple-wont-ship/

**Comment by cuongdo** [comment]
Thanks for your quick response! That seems to have worked around the issue.
