### ISSUE TITLE
Ability to add nested commands through `cobra add`

### ISSUE THREAD

**Issue by ianwalter** [spf13/cobra#266]
I would love to use `cobra add` to create nested commands, for example: 

```
cobra add db migrate
```

Cobra would then see that there are multiple arguments, create a directory called `db` if it doesn't exist and a command file inside of it called `migrate.go`. It would also create another file either inside of `db` or at the same directory level called `db.go` or `root.go` that will simply create a `dbCommand` so that nested commands can be added to it. I can submit a PR for this after my existing PR is resolved. Thanks.

**Comment by spf13** [comment]
@ianwalter I love the idea, please contribute this. 

If I can, I'll provide my ideas on what this feature should do/work like.

I think that the syntax should be `cobra add db/migrate`.
This would create `db.go` (if needed), `db/` (if needed) and `db/migrate.go`.
It would also add the appropriate `AddCommand(addCmd)` calls to support the tree structure. 

Currently the add command does support the `--parent` flag which does operate in a similar way, but requires more steps and doesn't put it in a subdirectory.

**Comment by ianwalter** [comment]
That sounds good to me. I will work on this. I must have missed `--parent`. Should I leave it intact? It seems to me that it's functionality would be completely covered by the proposed solution.

**Comment by spf13** [comment]
Lets leave it for now. It works slightly differently and supports a few use
cases this doesn't.

**Comment by waitingkuo** [comment]
Currently `cobra add db/migrate` does generate the subdirectory. But the behavior is strange. It generates a `var db/migrate = &cobra.Command{}`. Should we warn when the command contains "/" first?

**Comment by spf13** [comment]
I don't think it should warn. I think it should just do the right thing.
Seems like the only bug is how the variable name is created. Should we just
strip the "/"?

**Comment by kasisnu** [comment]
Looks like this bug still exists. I'm happy to work on this.

**Comment by spf13** [comment]
Please do :)

**Comment by Wulfheart** [comment]
@kasisnu what's the current status?

**Comment by geniass** [comment]
For me this doesn't create the subdirectory automatically.

Once I create the subdir, it creates a .go file inside it, but as discussed above the file has invalid syntax.

The next problem is that the subdir is considered a separate package (I think?)
Since the parent command, e.g. `rootCmd` is not exported, it can't be directly referenced.

@spf13  Should we make the parent command public? Add a public function? Something else?

**Comment by geniass** [comment]
I think this issue is a duplicate right?
https://github.com/spf13/cobra/issues/1059

**Comment by joshuabezaleel** [comment]
@geniass Yes, I think these 2 issues convey the same problem statement. 
I saw that there is a PR submitted already by @Wulfheart (?)

**Comment by Wulfheart** [comment]
Gonna reply later or in a few days.

**Comment by joshuabezaleel** [comment]
No worries. Will be happy to help and contribute if I can be of one @Wulfheart :slightly_smiling_face:

**Comment by johnraz** [comment]
@joshuabezaleel did you find / build a solution to this? 

Right now I managed to handle it by following the structure suggested here https://github.com/spf13/cobra/issues/641#issuecomment-404881159 but it makes the cobra cli kinda impossible to use with subcommands.

I'll attempt to summarise the situation with a simple example (and my very sparse Go knowledge):

We want to have a `parent` command exposing a child command `sub`.

The directory tree should look like:
```
├── cmd
│   ├── parent
│   │   ├── parent.go
│   │   └── sub.go
│   └── root.go
└── main.go
```

- Using `cobra add parent/sub` (do we agree on the syntax?) should create the `parent` directory if it doesn't exist.
- `parent.go` and `sub.go` should be part of the `parent` package 

### The `parent` package need to be somehow imported in order to be compiled.

**Solution 1**:

- The `rootCmd` could be made public by renaming to `RootCmd` in order to be importable in the `parent.go` file.
- The `parent` package should then be imported in the `main.go` file like this `import _ "github.com/whatver/cmd/db"` for the package to be picked-up by the compiler and added properly.

**Solution 2**:

- The `parentCmd` could be made public by renaming to `ParentCmd` in order to be importable in the `root.go` file.
- It could then be used in the `init` of the `root.go` file like this:
```
func init() {
	RootCmd.AddCommand(db.Cmd)
}
```
- Due to the fact that the `parent` package is now imported in `root.go`, it is picked up by the compiler and added properly.


@spf13 , @Wulfheart  any comments? 
Does that sound like a reasonable approach and something that you'd still like to see added to the cli command? 
Are there alternative approach?

Thanks for your time 😸

**Comment by rulisastra** [comment]
Hi @johnraz

I successfully follow your **` Solution 2`** but I am getting this error. 
````error
package github.com/whatver
        imports github.com/whatver/cmd
        imports github.com/whatver/cmd/parent
        imports github.com/whatver/cmd: import cycle not allowed
````

I don't know why. I have followed all your steps. I did try to delete the `init()` inside the `parent` package also, but it shows the same `cycle` error

**Comment by johnSchnake** [comment]
Since this is a cobra-cli issue I'm going to close; it can be opened again in the new repo: https://github.com/spf13/cobra-cli/issues/

@rulisastra without being able to see your code its hard to help with the import cycle. The files in `cmd/parent` should not refer to `cmd` package at all though.

Also worth noting: I think the decision to put commands into subdirectories instead of a single large directory has some pros/cons. A related ticket to boilerplate project structure has been opened as well https://github.com/spf13/cobra-cli/issues/12 and may be a good place to discuss that.

**Comment by lcarva** [comment]
I went ahead with the solution 2 proposed above. It seems like a natural way to organize sub-commands, especially if there are multiple levels.

Would you be open to having this added to the docs? I'm happy to contribute

**Comment by spf13** [comment]
Please contribute. Solution 2 seems like a viable approach.
