### ISSUE TITLE
Add support for versioning the binary

### ISSUE THREAD

**Issue by mattyjones** [spf13/cobra#282]
I would like to see first level support for versions with the help and default output of a binary. I would think just taking in a string and then spitting it right back out so the user could decide how/if they wanted versions.

``` golang
// RootCmd represents the base command when called without any subcommands
var RootCmd = &cobra.Command{
    Use:     "foo",
    Short:  short answer,
    Long: long answer,
    Version: fmt.Sprintf("(%s)", version.AppVersion()),
```

I would be open to writing the necessary code for this but before I put in the time I figured I would see if it would even be accepted and to get some feedback on it.

**Comment by MatejB** [comment]
Just a tip for other people landing on this issue.
Until first level support is added you can use solution similar to this one:
```go
// cliApp is used as a holder of root command.
type cliApp struct {
    cobra.Command
    Version     string
    Copyright string
}

func init() {
    app = &cliApp{
        Version: "1.0.0",
        Copyright: "some copy",
    }

    cobra.AddTemplateFunc("version", func() string { return app.Version })
    cobra.AddTemplateFunc("copyright", func() string { return app.Copyright })
    app.SetHelpTemplate("{{version}} {{copyright}}")
}
```

**Comment by nmiyake** [comment]
I'd be interested in seeing this implemented as well. Here's an implementation proposal:

At a high level:

* Add `Version string` as a variable to `Command`
  * If this variable is empty, then no behavior is changed. This will preserve back-compat for existing applications that define their own version flag.
* If `Version` is non-empty on the command being executed, add a `--version` flag that works similarly to `--help`
  * Flag is added to command being executed
  * If flag is present, version is printed using template (which can be set by user)
  * If flag is present at the top level, the `version` action is always executed (does not run any pre-run actions or delegate to subcommands)

This should be sufficient to support a top-level `--version` flag. This would not add a `version` command, but I think that this flag approach is the best generic one since it is fairly standard and the mechanism above should ensure that backwards compatibility is maintained with all previous Cobra applications.
