### ISSUE TITLE
child commands need to be unique

### ISSUE THREAD

**Issue by mattstratton** [spf13/cobra#362]
It's quite possible I'm missing something glaringly obvious here, but my situation is thus:

My command line application has subcommands, and the subcommands are not necessarily unique. For example, these use cases need to be supported:

`myapp event create`
`myapp event list`
`myapp sponsor create`
`myapp sponsor list`

The problem is, since the commands `create`, etc, are all thrown into the root of `cmd`, their names have to be unique. PR #273 has been outstanding since May, and I think it might solve for this, but is there another mechanism I'm missing?

**Comment by dmikalova** [comment]
I am also having an issue with this. My setup looks like this:

`myapp new note`
`myapp edit note`
`myapp get note`

If you run `myapp new note` or `myapp edit note` then `cmd.Parent().Name()` within `noteCmd` will return "get" instead of "new" or "edit" because get was the last one added.

I'm not sure this is the best layout either, it means that in each instance note has to handle the same set of flags. However `myapp note new --name` doesn't follow the suggested `appname verb noun --adj` scheme.

**Comment by bogem** [comment]
@dmikalova I don't think, your idea is possible. The parent of command is **pointer**, so if `note` is added to several commands, the parent of note will be only last parent, but it will be child for all parents. We also can't make parent command as non-pointer, because the flags of parent commands won't be updated and merged to child commands.
As temporary solution, you can make three note commands (one for `new`, `edit` and `get`). It's redundant and not elegant, but it will work how you want and I don't see any other solutions.

**Comment by bogem** [comment]
Another solution is copying commands.
You can create general note command with all flags you want and then create `newNoteCmd`, `editNoteCmd` and copy general note command to them. 
Example:
```go
package main

import "github.com/spf13/cobra"

var rootCmd = &cobra.Command{ Use: "myapp", ... }
var generalNoteCmd = &cobra.Command{ Use: "note", ... }
var newCmd = &cobra.Command{ Use: "new", ... }
var newNoteCmd = &cobra.Command{}

func init() {  
  // Add flags to generalNote
  generalNoteCmd.Flags()... 
  generalNoteCmd.Flags()...

  *newNoteCmd = *generalNoteCmd
  newCmd.AddCommand(newNoteCmd)
  rootCmd.AddCommand(newCmd)
}
```

**Comment by bogem** [comment]
Did it solve your problem, @mattstratton @dmikalova?

**Comment by dmikalova** [comment]
I was able to work around this by just creating multiple instances. It's more boilerplate but ends up being more flexible with the differences in each command.

**Comment by bogem** [comment]
You can also use the constructor for commands:
```go
var rootCmd = &cobra.Command{ Use: "myapp", ... }
var newCmd = &cobra.Command{ Use: "new", ... }
var editCmd = &cobra.Command{ Use: "edit", ... }
var getCmd = &cobra.Command{ Use: "get", ... }

var newNoteCmd = newNoteCmd()
var editNoteCmd = newNoteCmd()
var getNoteCmd = newNoteCmd()

func init() {
    newCmd.AddCommand(newNoteCmd)
    editCmd.AddCommand(editNoteCmd)
    getCmd.AddCommand(getNoteCmd)

   rootCmd.AddCommand(newCmd)
   rootCmd.AddCommand(editCmd)
   rootCmd.AddCommand(getCmd)
}

func newNoteCmd() *cobra.Command {
    return &cobra.Command{
        Use: "note",
        ...
    }
}
```
