### ISSUE TITLE
bash auto complete should add space at the end of a completed command

### ISSUE THREAD

**Issue by rabbah** [spf13/cobra#371]
The bash auto completion generation does not add a space at the end of a completed command. This is not consistent with usual shell completion; and it's generally more convenient to add a space after the completion, isn't it?

**Comment by eparis** [comment]
I thought (and this is just what I remember from writing this months ago) that we were 'supposed' to add a space most places. 

If you had two flags `argflag` and `noargflag` and did
`--argfla[tab][tab]` should complete to `--argflag=`
`--noargfla[tab][tab]` should complete to `--noargflag[space]`

If it is not doing that it sounds like a bug. Not sure I'd ever get back to work on it though....

**Comment by rabbah** [comment]
This is how our CLI is behaving with bash tab completion:

```
> wsk acti[tab]
action      activation

> wsk activation[tab]
activation

> wsk activation [tab]
get     list    logs    poll    result  

> wsk activation get[tab]
get

> wsk activation get -[tab]
--apihost= 
--verbose 
# others elided

> wsk activatioon --ver[tab][tab]
--verbose

> wsk activation --apiho[tab][tab]
wsk activation get --apihost=--apihost=
```

I don't rule out that our CLI is using the auto completion generation incorrectly.
I suppose we should rule that out first?


```

**Comment by johnSchnake** [comment]
FYI for future folks looking at this: the linked issue/conversation indicates this may only be a problem on MacOS.

**Comment by marckhouzam** [comment]
> FYI for future folks looking at this: the linked issue/conversation indicates this may only be a problem on MacOS.

I think this issue is related to the change in #178.
The details are tricky, but I'll try to express my understanding.

1. bash completion sometimes turns off adding a space after the completion, for example after a flag using the `=` form (e.g., `--flag=`).  To turn off adding a space, the bash `compopt` command is used.
2. `compopt` does not exist for bash 3
3. MacOS was running bash 3
4. #178 added logic to not call `compopt` if it didn't exist.  But then it was no longer possible to turn off spaces, and it seems that same PR then chose to never add a space, even when there should be one as a fix.

Notice the `-o nospace` here: https://github.com/spf13/cobra/blob/5414d3d45d41008846e74d0f7768363014f3f5c0/bash_completions.go#L425
which is only run if `compopt` is not found.

Since this situation only affect bash3 and has been the behaviour for so long, I would be inclined to close this as "won't fix".

What do you think @johnSchnake ?

**Comment by rabbah** [comment]
Thanks for the detailed explanation @marckhouzam.

**Comment by johnSchnake** [comment]
I will bow to @marckhouzam's expertise on the shell completions. It does sound like its a bit of a muddle with osx/bash versions and doing the best we can.
