### ISSUE TITLE
Best way to call a (sub)-command programmatically?

### ISSUE THREAD

**Issue by michaelfavia** [spf13/cobra#379]
I'd like to have an "install" command that programmatically calls 3+ commands that each individually register themselves as sub-commands with "install" as their parent.

I'm sorry if I missed it but I wasn't able to see what would be the best way to execute a command from within the context of the parent command. Thanks for any guidance!

**Comment by dmikalova** [comment]
Add install to the root with subcommands:
`RootCmd.AddCommand(installCmd)
installCmd.AddCommand(aCmd)
installCmd.AddCommand(bCmd)
installCmd.AddCommand(cCmd)`

Define a bare install to run a, b, and c. installCmd.Run is only run if none of the subcommands are provided.
`var installCmd = &cobra.Command{
	Use:   "install",
	Short: "",
	Long:  ``,
	func(cmd *cobra.Command, args []string) {
		aCmd(cmd, args)
		bCmd(cmd, args)
		cCmd(cmd, args)
}

**Comment by garrettlove8** [comment]
> ```
> var installCmd = &cobra.Command{
> 	Use:   "install",
> 	Short: "",
> 	Long:  ``,
> 	func(cmd *cobra.Command, args []string) {
> 		aCmd(cmd, args)
> 		bCmd(cmd, args)
> 		cCmd(cmd, args)
> }
> ```

Not sure if something has changed in Cobra since this issue was written, but assuming `aCmd`, `bCmd`, and `cCmd` are just `&cobra.Command`, looks like they can't be run that way since they aren't functions...

**Comment by n1rna** [comment]
You should call the `Run(*cobra.Command, []string)` method on the command instances.

Provided example now should used like:
```
var installCmd = &cobra.Command{
	Use:   "install",
	Short: "",
	Long:  ``,
	func(cmd *cobra.Command, args []string) {
		aCmd.Run(cmd, args)
		bCmd.Run(cmd, args)
		cCmd.Run(cmd, args)
}
```

**Comment by migueleliasweb** [comment]
The above suggestion doesn't seem to work anymore. 

I keep getting `panic: runtime error: invalid memory address or nil pointer dereference` when calling the other command. I tried adding the command to be called as a subcommand of the command being run directly but even that didn't work.

:/

**Comment by migueleliasweb** [comment]
There is some caveats to the above solution. Yes, it works and calling `Run()` will actually run the command but this introduces some issues on more complex commands as calling `Run()` directly won't call any other hooks such as `PostRun()` or `Args()`.

For context: I'm calling `mygobin cmdA` and I want to internally call `cmdB`.

There is a workaround but it also comes with a caveat. The `cobra.Command` struct provides a standard way to call commands and it creates the workflow for the hooks to be called in the correct order, the method is called `.Execute()`.

The issue is that when you call another command's `Execute()` method, it will also call its parent `Execute` which in turn will call the original command again and then it will call the subcommand again...and so on. This is an infinite loop.

The workaround for this is to remove the `rootCmd.AddCommand` call from the command being called programatically (in this case `cmdB`). This will make it so there is no infinite loop but it also means this command is not callable from the CLI anymore - only through this "proxy" command.
