### ISSUE TITLE
If no subcommand, how to get args?

### ISSUE THREAD

**Issue by kk44** [spf13/cobra#42]
example:

``` go
package main

import (
    "fmt"
    "github.com/spf13/cobra"
)

func main() {
    var echo = &cobra.Command{
        Use:    "echo [string...]",
        Short:  "echo all strings",
        Long:   "echo string string string string...",
        Run:    func(cmd *cobra.Command, args []string) {
            fmt.Printf("%v\n", args)
        },
    }

    echo.Execute()
}
```

```
[bash]# go run echo.go aa bb cc dd

Usage:
  echo [string...] [flags]

 Available Flags:
  -h, --help=false: help for echo
Error: unknown command "aa"
Run 'help' for usage.

echo: invalid command [`aa` `bb` `cc` `dd`]
Run 'echo help' for usage
```

```
[bash]# go run echo.go echo aa bb cc dd
[echo aa bb cc dd]
```

```
[bash]# go run echo.go
[]
```

Thanks!

**Comment by ghodss** [comment]
I'm also having this issue. Is having zero subcommands supported? It doesn't seem to be working.

**Comment by eparis** [comment]
It isn't possible.  The code treats the root command "special".  I don't really love it.

Root commands my only take flags and subcommands. Validation for subcommands is only done for root commands.

Subcommands will be called with an argument instead of failing if an invalid sub-sub-command was intended, but typod.

I'm thinking about what to do here in https://github.com/spf13/cobra/pull/86

But any kind of consistency is going to break previous behavior. Personally I'm leaning towards a 'takesNoArgs' flag which defaults to false. Meaning the root command, and all subcommands, would get unknown args.

You would only get subcommand validation and complain if you set takesNoArgs=true

**Comment by viktorbenei** [comment]
We recently started to migrate from codegangsta / urfave CLI, and we love Cobra so far! But we have a couple of tools which are primarily designed to run other programs (think about something `/usr/bin/env` or `/usr/bin/ssh`, but with a couple of utility commands like `init` built into the tool), and we can't figure out how we could do that with Cobra.

IMO what @ghodss described (and what's essentially how this works in codegangsta / urfave CLI) at https://github.com/spf13/cobra/pull/120#issuecomment-116910479 / https://github.com/spf13/cobra/pull/86#issuecomment-102215537 makes sense, or be able to specify a "default" command in any other way.

Is there a workaround for this use case for now?

**Comment by viktorbenei** [comment]
I think this issue is also pretty much the same as https://github.com/spf13/cobra/issues/15

**Comment by dnephin** [comment]
If you use my PR #284 and use `cobra.ArbitraryArgs` as the `Args` value, you get this behaviour.

**Comment by viktorbenei** [comment]
@dnephin checked the PR and it's not exactly clear for me: does this work for the Root command too?

**Comment by dnephin** [comment]
Yes, it will work for the root command. The old args behaviour is defined in `legacyArgs` (https://github.com/spf13/cobra/pull/284/files#diff-07ee57a49d1c0b692bd79676cc31dd6fR9). If you set any other `Args` it wont use the `legacyArgs()` behaviour.
