### ISSUE TITLE
provide preRun/postRun hooks

### ISSUE THREAD

**Issue by zyndiecate** [spf13/cobra#47]
It would be really cool if cobra provides hooks for the commands `Run` function. That way things could happen right before/after the `Run` function is executed. For the `PreRun` hook it would be cool when flags are already parsed and usable inside the hooks. 

Opinions?

**Comment by zepouet** [comment]
Hello, 

I agree with you. At the moment I use Cobra to develop a extended client for docker because all the days. Sometimes I need to ask a question before the action. For example before to kill the contairers.
I do that with 

fmt.Print("\n[Warning] Are you sure to kill them [Yes/No] : ")
var input string
fmt.Scanf("%s", &input)

**Comment by AlexanderThaller** [comment]
Would pre/post hooks like in my pull request suffice? https://github.com/spf13/cobra/pull/53

**Comment by zyndiecate** [comment]
Haven't tested yet, but looks like it solves the problem. :+1:

**Comment by eparis** [comment]
Closing as these have been merged...
