### ISSUE TITLE
Don't allow short and longhand arguments to be interlaced?

### ISSUE THREAD

**Issue by chrischris292** [spf13/cobra#601]
If I have an argument *short* -f and *long* --file, I'm wondering if there's a clean way to enforce the user from not inputing -file. Right now it will read -f with input "ile"

**Comment by johnSchnake** [comment]
> to enforce the user from not inputing -file

I'm not sure what this means exactly; you want to prevent users from ever using the shorthand? The long/short parsing tries to follow POSIX standards as much as possible so I don't anticipate there is an intent to reject short flags or something like that. If you allow `-f` then you're going to have to allow `-f<anything>` because that's what it means to allow `-f`. You can just not specify a short flag if thats a problem for you.

Closing due to age/activity.
