### ISSUE TITLE
How to pass parameters from one command to another?

### ISSUE THREAD

**Issue by kev5** [spf13/cobra#710]
This might not be an issue, but I couldn't find any example for this. Suppose I have a `login` command in my CLI which asks for a username and password from the user. How can I use the same username and password while trying to execute any other command which requires it later? Can I store the username and password obtained through the `login` command in flags or some other variables which can be called from other CLI commands? If yes, can I see a working example of it?

I tried following the documentation for setting my flags but it doesn't seem to work because maybe I'm not doing it properly. A small example would be great. Thank you.

**Comment by kev5** [comment]
@eparis Any help with this? Thanks!

**Comment by patrick-motard** [comment]
@kev5 Are you envisioning something like:

```
myApp login --user patrick --password *******
Log In Successful!

// myApp gets user metadata if user is logged in
myApp user --get
{
  "user": "patrick",
  "favorite-color": "blue",
  "hobby": "fishing"
}
```

If so, it sounds like you're asking for cobra to do state management. To my knowledge, cobra does not do that. Each time you invoke `myApp` by issuing a command the program is loaded into memory (RAM) and executed. Anything that is loaded into memory during that execution is lost unless you choose to store it on the file system for later retrieval.

As an aside, in the example of a `login`, that password would be sensitive, you wouldn't want to store that in the application in memory or on the file system unencrypted.

I'm working on an app that uses cobra that has a similar need. I have state that needs to be shared between calls to the app. Most commands in my app need to read from settings and do some action. Other commands need to perform an action and store the results somewhere so that it knows to perform those same actions again the next time its called. I started off by using a JSON file to store the output of my commands. All my commands read and write to that file.

I have an additional requirement of wanting to allow users to provide their own configuration file that they can modify themselves without using the program I'm writing. JSON isn't the most fun to modify, and it doesn't allow for comments, whereas TOML does. So I thought of using TOML, and then I remembered Viper, which is also written by @spf13, which integrates well with Cobra, and handles reading from a config file. On top of that it supports JSON _and_ TOML! Perfect! 

The only thing it doesn't seem to support is writing to the config file, or at least I'm not seeing that feature in it's documentation yet. So my app still has to have code in it to write to the config file, but that's not so bad.

In your case if you're doing user login, saving the username and password to a file probably isn't the best idea. You're better off finding an authentication/authorization library in golang and adding that to your application. Managing a users login session is a whole other set of challenges that go beyond the challenge of sharing state between invocations of  your cobra app. Hope this helps!

**Comment by xuanskyer** [comment]
the same Q

**Comment by hitzhangjie** [comment]
the same Question.

**Comment by marckhouzam** [comment]
From what I know, each command given to the Cobra program runs the program from scratch each time.  That means that to persist information from the execution of one command to an another you need to store that information outside the program. Or at least I don't know of another way to do it.

You could use a file for example.  If it's for a password, you could encrypt it before storing it.  Then the following commands would check for the file, decrypt it and use the password.

**Comment by johnSchnake** [comment]
Asked and answered; since no follow up recently going to close this.
