### ISSUE TITLE
Required flags are not enforced in subcommands

### ISSUE THREAD

**Issue by terra-nova** [spf13/cobra#723]
Hi,

let's say I have some command "foo" with a mandatory parameter "bar":

```
var fooCmd = &cobra.Command{
	Use:   "foo",
}
...
func init() {
	fooCmd.PersistentFlags().StringVar(&bar "bar", "", "...")
	fooCmd.MarkFlagRequired("bar")
	rootCmd.AddCommand(fooCmd)
}
```

Testing this works just fine, I get an error message if the "bar" flag is omitted on the command line.

Now I want to add a subcommand "frobozz" to "foo":

```
var frobozzCmd = &cobra.Command{
	Use:   "frobozz",
	...
}
...
func init() {
	fooCmd.AddCommand(frobozzCmd)
}
```

But I now find that the presence of the "bar" parameter is not enforced for the "frobozz" command. Is this by design/intentional?

**Comment by raphaelDL** [comment]
Use  

`fooCmd.MarkPersistentFlagRequired("bar")`

 instead of 

`fooCmd.MarkFlagRequired("bar")`

when marking it as required, since the last one will enforce it only when calling your root command alone.

 `fooCmd.MarkPersistentFlagRequired("bar")` will enforce it for all your root subcommands.

You can restrict enforcement to a single subcommand  by setting it in your subcommand:

```
func init() {
        fooCmd.MarkPersistentFlagRequired("bar")
	fooCmd.AddCommand(frobozzCmd)
}
```

**Comment by terra-nova** [comment]
Ah, that makes sense. Thank you for the detailed explanation.
