### ISSUE TITLE
Support for standard single dash flags?

### ISSUE THREAD

**Issue by darkfeline** [spf13/cobra#740]
The documentation seems unclear on this point, but I'm guessing the answer is no.

The README says "Cobra supports [...] the Go flag package." except it does not parse single dash flags the same way, and there does not appear to be a way to enable this behavior.  This means that cobra cannot be used transparently alongside other tools which may be using the standard flag package (to restate, if I have a dozen Go tools all using the standard flag package, moving one of them to cobra makes that one inconsistent with all of the other tools).

**Comment by Fjolnir-Dvorak** [comment]
That is true, but as far as I know, or as I understand it, exactly that is what is intended by Pflags. Cobra is using Pflags instead of Flags. Pflags stands for Posix-flags and posix does not allow single dashed words.

Reference: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

**Comment by Fjolnir-Dvorak** [comment]
https://github.com/spf13/cobra/pull/485#issuecomment-418932103
spf13 wrote something about the design decisions in that pull request. That could make it more clear why the "go"-style is not supported.
But yes, the readme is a little bit unclear with the go flag package.
