### ISSUE TITLE
unknown command is printed twice

### ISSUE THREAD

**Issue by yoni386** [spf13/cobra#744]
Default output for "unknown command" is getting printed two times. 

For example:
The command is given command is "pri1" and the actual one is "print"

```
subcommand pri1 return 
Error: unknown command "pri1" for "hoster"

Did you mean this?
        print

Run 'hoster --help' for usage.
unknown command "pri1" for "hoster"

Did you mean this?
        print

```

**Comment by lornajane** [comment]
This happens because the error is output both when it happens https://github.com/spf13/cobra/blob/master/command.go#L841-L842 and probably in your `cmd/root.go` also. Removing `fmt.Println(err)` from my `Execute()` function in the root command has stopped this showing twice but if any other error is returned, it won't be output so this might not be the best solution!

**Comment by johnSchnake** [comment]
You can also disable cobra from automatically printing the error or usage messages.

Closing as part of #1600.
