### ISSUE TITLE
Document a best practice for testing a cobra app

### ISSUE THREAD

**Issue by sethcenterbar** [spf13/cobra#770]
Hey there, I'm quite new to go and cobra, but I'm leveraging the framework to build some tools for work and loving it. 

I've been trying to set up testing for my project, but I'm wondering how other people using cobra are implementing testing for sub-commands. The typical go example led me to believe that in the cmds folder, i would make a command x.go and then create a test x_test.go. Because of the way that all of the commands are passed to the root command, I don't believe this is possible. 

To other users, how would you suggest doing testing on your sub-commands? If this isn't just a noob misunderstanding, maybe it would be good to add a best practice for testing into the main readme?

**Comment by shilangyu** [comment]
Could anyone share how they write tests for sub-commands? I am also stuck i find it really hard to write any kind of test for a more complex sub-command. Thanks

**Comment by jsenon** [comment]
I've found an example here https://chromium.googlesource.com/external/github.com/spf13/cobra/+/refs/heads/master/command_test.go

**Comment by lpabon** [comment]
If you are coming here from Google, in our project we wrapped the var and init sections of the commands in functions so that they can be called by unit tests and re-initialize all variables.

* [Example command](https://github.com/portworx/px/blob/cb2e24b09cd1dbeadd3cf5f736882af56fae7110/cmd/version.go#L30-L55)
* [Registration of the command](https://github.com/portworx/px/blob/cb2e24b09cd1dbeadd3cf5f736882af56fae7110/cmd/main.go#L116-L147)
* [Changed the Execute function to call Main](https://github.com/portworx/px/blob/cb2e24b09cd1dbeadd3cf5f736882af56fae7110/cmd/main.go#L106-L111)
* [Now unit tests can call executeCli](https://github.com/portworx/px/blob/cb2e24b09cd1dbeadd3cf5f736882af56fae7110/cmd/common_test.go#L99-L103) to test their calls

**Comment by tiagotele** [comment]
Hi! I think you can get inspiration from who are using Cobra like [helm]https://github.com/helm/helm/tree/master/cmd/helm) or [kubectl](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd_test.go)

**Comment by igomez10** [comment]
Hi! @lpabon your links are broken. Could your reupload? :pray:

**Comment by marcellodesales** [comment]
@lpabon Maybe the repo `px` is private?

**Comment by red8888** [comment]
it would be nice to have guidance or even some kind of default skeleton which includes a test director and hooks that up in an opinionated way. instead of having to search around for how everyone else is doing it their specific quirky way

**Comment by myaut** [comment]
Thanks for the reference test implementation, it was helpful. However, i'm struggling with resetting flags to default values. I've ended up with this monstrosity:
```
func resetFlags(cmd *cobra.Command) {
	cmd.Flags().VisitAll(func(flag *pflag.Flag) {
		if flag.Value.Type() == "stringSlice" {
			// XXX: unfortunately, flag.Value.Set() appends to original
			// slice, not resets it, so we retrieve pointer to the slice here
			// and set it to new empty slice manually
			value := reflect.ValueOf(flag.Value).Elem().FieldByName("value")
			ptr := (*[]string)(unsafe.Pointer(value.Pointer()))
			*ptr = make([]string, 0)
		}

		flag.Value.Set(flag.DefValue)
	})
	for _, cmd := range cmd.Commands() {
		resetFlags(cmd)
	}
}
```
Is there a better way to reset flags?

**Comment by rdeusser** [comment]
@myaut Cobra does have a [ResetFlags()](https://pkg.go.dev/github.com/spf13/cobra#Command.ResetFlags) method. Does that help you at all?

**Comment by marcellodesales** [comment]
* I decided to test the CLI business logic instead of testing the actual flags/params... 
  * Which are actually tested here... 
* Expose a private method in the command file to be tested, where the command is called after verifying the paramters
  * https://github.com/marcellodesales/cloner/blob/master/cmd/git.go#L36-L64
* An example of the test cases is at https://github.com/marcellodesales/cloner/blob/master/cmd/git_test.go#L26
  * Calling a strategy method defined in the root CMD test that calls a private method locally
  * https://github.com/marcellodesales/cloner/blob/982d0f59dbe56e224056939b95b52fefcf8a0de1/cmd/root_test.go#L77

**Comment by KEINOS** [comment]
It's been 2 years but still +1 for the issue.

Any best-practice-article or samples for testing `cobra` will help me a lot.

As a Golang beginner, even a simple "Hello, world!" command which has a "hello" sub-command with best practices and tests that cover 100% of coverage would help. I never get covered the last few percentages ...

**Comment by g14a** [comment]
Hey folks, I've struggled with testing sub commands myself and somehow managed to finally achieve it. And I wrote an article about it. https://g14a.github.io/posts/Testing-Cobra-Subcommands

@sethcenterbar @shilangyu 
This thread helped me a lot in this particular concept. So just wanted to thank you as well ❤️❤️

**Comment by sethcenterbar** [comment]
> Hey folks, I've struggled with testing sub commands myself and somehow managed to finally achieve it. And I wrote an article about it. https://g14a.github.io/posts/Testing-Cobra-Subcommands
> 
> @sethcenterbar @shilangyu
> This thread helped me a lot in this particular concept. So just wanted to thank you as well ❤️❤️

Very cool, I'll check it out soon! Thanks for writing an article :)

**Comment by Aisuko** [comment]
I still wonder if there exists a simple case for testing the subcommand, I am a little bit struggling with this. Welcome more people sharing the test cases.

**Comment by karkir0003** [comment]
> Hey folks, I've struggled with testing sub commands myself and somehow managed to finally achieve it. And I wrote an article about it. https://g14a.github.io/posts/Testing-Cobra-Subcommands
> 
> @sethcenterbar @shilangyu This thread helped me a lot in this particular concept. So just wanted to thank you as well ❤️❤️

unable to access the link
