### ISSUE TITLE
Suggestion: "did you mean" for misspelled commands

### ISSUE THREAD

**Issue by synful** [spf13/cobra#78]
In git, if you execute `git commt`, you'll get the following message:

```
git: 'commt' is not a git command. See 'git --help'.

Did you mean this?
	commit
```

It would be a very useful (and simple to implement) feature for Cobra to have. Thoughts?

**Comment by pravj** [comment]
Hi All,

This is a nice feature to have.

Although, I'm not sure it's right to have it here or not, because *git* has all the *commands* all the time, but in our case users may or may not have that much commands.

If we're going ahead, I'll propose some *similarity index* that returns N most similar commands to what users have entered. *Git* seems to be the doing same https://github.com/git/git/blob/master/help.c

**Comment by synful** [comment]
I think that's a good way to go, although I think it'd be best to add a utility feature which would automatically pick the most similar command(s) which matched some similarity threshold and print them. Presumably we'd want this feature to be off by default.

**Comment by eparis** [comment]
#149

**Comment by fabianofranz** [comment]
This should be fixed by https://github.com/spf13/cobra/pull/149 and https://github.com/spf13/cobra/pull/163.

**Comment by marians** [comment]
Just recognized this got implemented. Thanks!
