### ISSUE TITLE
How to exit after a help command

### ISSUE THREAD

**Issue by rhugga** [spf13/cobra#829]
I'm using the default built in help command. 

When someone issues ./mycmd --help or ./mycmd subcmd --help, it displays the help as expected but then it doesn't exit and I can't figure out where or how to do this.

I would think this would be part of the command.

**Comment by bacongobbler** [comment]
Can you share some sample go code to demonstrate your issue?

**Comment by jharshman** [comment]
@rhugga, I cannot recreate the issue.

**Comment by codingbaobao** [comment]
Hi, I have a sample code to reproduce the issue
```
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number of Hugo",
}

func main() {
	versionCmd.Execute()
	fmt.Println("I'm still here")
}
```
I was expect it will run os.exit() when calling `./mycmd -h` like pflags, however it continue executing the code below Execute().

**Comment by marckhouzam** [comment]
Hi @codingbaobao, you should always check the return value for `Execute()` to see if there was an error.  I don't believe Cobra ever calls `os.Exit()` but leaves the flexibility to the program to choose what to do by returning it error codes.

**Comment by codingbaobao** [comment]
Hi @marckhouzam, thanks for your reply. I didn't write error check just for make it simple. In fact, the return value won't return any error when calling help, so you can't distinguish the difference. 
btw, here is my package version:
cobra v1.5
pflag v1.0.5

**Comment by marckhouzam** [comment]
You are right @codingbaobao, I now see that the error is swallowed by Cobra after printing the help: https://github.com/spf13/cobra/blob/dbf85f6104904d539cabceebec234e817fa0df0c/command.go#L994-L997

Hmm, I wonder if this is still ok?  Asking for the help is a valid command and the code then returns in the same way as a valid command.

Can you clarify your usecase?

**Comment by codingbaobao** [comment]
Hi @marckhouzam, sorry for the late reply. I don't think exit the program after calling help is a normal case, since calling help means the user don't know how to use it and wants to know, which means there's nothing the program needs to run.

I may agree that throwing error than calling exit internally is a nice idea, since some program may set up something in begin and needs to clear it, but calling help without even an error is kind of strange honestly.

At least in my experience, I haven't see any cli not exit when calling help.

**Comment by mrexmelle** [comment]
Hi @marckhouzam , a new Cobra user here. I also wonder how to exit an app after a switch is triggered?

[The code snippet](https://github.com/spf13/cobra/issues/829#issuecomment-1227021572) attached by @codingbaobao can still be used for my case.

I am expecting the following result:
```
$ app version
Print the version number of Hugo
```

Not the following:
```
$ app version
Print the version number of Hugo
I'm still here
```

This `version` case is an extremely common implementation in pretty much every CLI app in the world.
As an example, when you call `$ go version`, it will display
```
go version go1.19.4 darwin/arm64
```
Instead of:
```
go version go1.19.4 darwin/arm64
{{ and suddenly executing a go build here }}
```

So, the question is: How to exit the app after it completes printing the version of the app?

**Comment by codingbaobao** [comment]
Hi @mrexmelle , actually i have changed my program workflow to fit this. I think there is a common view in cobra community on how to trigger command, which is `main()` should only contains cmd.Execute() and error check, your pre-processing and post-processing should call by `PreRun()` and `PostRun()`.

The overall pattern should look like this:
```go
var versionCmd = &cobra.Command {
	Use:   "Foo",
	Short: "Foo the world",
	PreRun: func(cmd *cobra.Command, args []string) {
		// Set up env
	}
	PostRun: func(cmd *cobra.Command, args []string) {
		// Clean up
	}
}

func main() {
	if err := versionCmd.Execute();err!=nil{
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by mrexmelle** [comment]
Thanks for sharing @codingbaobao! I also learn that, as you mentioned, we need to change our paradigm when using Cobra. There should be no main functionality takes place in `main()`. The main functionality should run in a switch.

For example an app named `app`, shouldn't have its main functionality runs with only `./app` call. The main functionality should run when `./app run` or `./app serve` is called.

When a bare `./app` is called, it should display help menu instead of running its main functionality.

**Comment by chazer** [comment]
It may be useful to someone.
My decision:
```golang
func ApplyExitOnHelp(c *cobra.Command, exitCode int) {
	helpFunc := c.HelpFunc()
	c.SetHelpFunc(func(c *cobra.Command, s []string) {
		helpFunc(c, s)
		os.Exit(exitCode)
	})
}

func main() {
	ApplyExitOnHelp(rootCmd, 0)

	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	// ...
}
```
