### ISSUE TITLE
align expected flag data type

### ISSUE THREAD

**Issue by pjebs** [spf13/cobra#856]
```
Flags:
  -d, --date-range strings   date range (using input csv time format) (default [,])
  -f, --fields strings       csv field names (separated by comma) (default [timestamp,value])
  -h, --help                 help for csv
      --itf string           input csv time format (ref: https://golang.org/pkg/time/#pkg-constants) (default "2006-01-02")
      --order-by string      order by "ASC" or "DESC"
      --otf string           output csv time format (ref: https://golang.org/pkg/time/#pkg-constants) (default "2006-01-02")
  -o, --out string           output file name (default "export.csv")
  -s, --store int            store identifier (1-1115) (default 698)
```

it would be good if cobra aligned the expected flag data types for flags.

**Comment by johnSchnake** [comment]
Is this really a problem? I checked a few other tools I had locally and none of them aligned that as a separate column. I think by keeping the data type by the flag itself it makes it more readable too; the idea of an aligned column would be useful if that data would be useful to read on its own but just a column of `string string int string` doesn't add much value.

Since this is almost 3y old I'm going to close as part of #1600; if you want to discuss further feel free to reopen.

**Comment by avamsi** [comment]
@johnSchnake would you be open to reviewing a PR for this?

**Comment by avamsi** [comment]
@marckhouzam as they seem to be more active (aside: I created https://github.com/avamsi/climate, which heavily uses Cobra under the hood, so would love to help maintain Cobra).

**Comment by avamsi** [comment]
For posterity, I was looking at the fix anyway and it needs to be to spf13/pflag (whose last commit is more than 2 years old?!) -- https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L723-L749.
