### ISSUE TITLE
about hcl LICENSE

### ISSUE THREAD

**Issue by qingguee** [spf13/cobra#960]
Hello, 
Our software is using cobra, so we'd like to know have cobra modify anything about hcl?
I guess cobra didn't, but could you help to confirm?

On, page below, hcl is using MPL. So, if I understand correctly, if corbra modify hcl, then corbra need be MPL. 
https://github.com/hashicorp/hcl/blob/master/LICENSE

BRs,
Fan

**Comment by umarcor** [comment]
Hi @qingguee! IANAL, but hashicorp/hcl is NOT a direct dependency of cobra. See https://github.com/spf13/cobra/blob/master/go.mod. It is a direct dependency of spf13/viper, though (see https://github.com/spf13/viper/blob/master/go.mod). Therefore, I think that the appropriate location for this issue is https://github.com/spf13/viper/issues.

**Comment by qingguee** [comment]
You are right. I will file a issue to viper. 
Thank you so much. 

BRs,
Fan
