### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by bep** [spf13/cobra#99]
Tried to generate Bash autocompletion for Hugo, but gets:

```
__start_hugo:3: command not found: _init_completion
```

I don't see `_init_completion` anywhere in the source.

**Comment by bep** [comment]
@eparis any tips?

**Comment by eparis** [comment]
_init_completion is supposed to be included either with bash or with the bash_completions package...

**Comment by eparis** [comment]
I guess we need to have it fail silently instead of letting users know they need bash-completions > version 1.90 (I think that's where it was added)

I wouldn't want a noisy failure in a script loaded at login....

**Comment by eparis** [comment]
http://anonscm.debian.org/cgit/bash-completion/bash-completion.git/tree/bash_completion#n669

**Comment by eparis** [comment]
I could probably switch to _get_comp_words_by_ref which seems to be even older...

_get_comp_words_by_ref: ver 1.2 was June 2010
_init_completion: ver 1.90 was Nov 2011

I'll take suggestions, but it seems to me like Nov 2011 should recent enough support...

**Comment by bep** [comment]
In my case I was trying to get it running under zsh --- It runs fine on my Ubuntu 14.10. I will close this as "my fault".

**Comment by eparis** [comment]
I haven't looked at zsh, but it might be relatively easy to support, dunno.....

**Comment by marcmo** [comment]
this also causes problems under Mac OS using `brew`. The default bash-completion version you get with `brew` is too old.
Installing the *newer* version is a no-go for some since it requires to switch to a newer bash version (4.x) but OS X only ships with 3.x.
why not support the older bash-completion? what's the drawback?

~~~.bash
~ > bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
~ > brew info bash-completion
bash-completion: stable 1.3 (bottled)
Programmable bash completion
https://bash-completion.alioth.debian.org/
~ > system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.4 (14E46)
      Kernel Version: Darwin 14.4.0
~~~

**Comment by eparis** [comment]
The only 'drawback' is that I don't have a Mac and don't use 5 year out of date bash-completion. So I don't know how to do it. _init_completion (and in turn __get_comp_words_by_ref) are incredibly complex functions I can't truly understand and so I will not copy them wholesale into our codebase (as then we have to maintain them, and I'm just not up to the task)

If someone writes a 'simple' patch which adds compatibility further back, I'd be REALLY happy to take it. (where simple means I can understand it). I have no idea what is or isn't possible on a mac. Maybe it has _comp_words_by_ref and you can find a way to switch to that directly?
