### ISSUE TITLE
Writing test for cobra-viper go package

### ISSUE THREAD

**Issue by abhishekjoy1** [spf13/cobra#990]
I have cloned a cobra and viper based go application. Here commands are invoked using cli as follows: 
      `./<my go tool> <command>  --<command-flag1>` 

And code snippet for the same is as follows:

      package cmd

      import (
	   "fmt"
	   "os"
	   "github.com/spf13/cobra"
	   "github.com/spf13/viper"
      )

      var viperCon *viper.Viper
      var cmd1 = &cobra.Command{
      Use:   "cmd1",
      Short: "Do xyz",
      Long:  "Do xyz",
      Run: func(cmd *cobra.Command, args []string) {
	   config := getConfig(viperCon)
	   res, err := myTool.ExecCmd(config)
	   if err != nil {
		 fmt.Println(err)
		 os.Exit(1)
	   }
     }

     func init() {
       rootCmd.AddCommand(cmd)

       // set the config provided by the flags and default values
       viperCon = setConfig()
       ...
     }

I am going to write tests for all such commands to see if they are working fine. Any pointer/code erefernce on this regarding how to start would be great.

**Comment by johnSchnake** [comment]
Good question about how to test a CLI application. I know its long overdue and I'm sorry you didnt get more feedback when asked. Its a vague question with lots of possible answers so I'm guessing with limited bandwidth people passed on replying.

In any case, I maintain the [Sonobuoy](github.com/vmware-tanzu/sonobuoy) and we use cobra, not as much viper. You can see some of the integration tests here: https://github.com/vmware-tanzu/sonobuoy/blob/main/test/integration/sonobuoy_integration_test.go#L174

When possible, I like to just avoid going through the codepaths that require cobra/viper tbh. I'd rather have tests that target the business logic and then separate tests to see that the cmdline and env stuff gets interpreted correctly. So you can see in the integration test above that its actually shelling out to the binary and running it. In some test cases we are checking pass/fail, others we are checking exact input. But by doing it this way it is _actually_ testing the CLI tool after its built.

Sometimes you'll find issues/differences from when its invoked via code vs ran by an operator in an integration test.

Since there was little other activity on this, per #1600 I'm going to go ahead and close this. Feel free to reopen to discuss if necessary.
